### ISSUE TITLE
new feature: reset task runs

### ISSUE THREAD

**Issue by luddwichr** [Scifabric/pybossa#1065]
In the project group for which I am maintaining a PyBossa instance, it was found useful to have a function that allows to reset the task-runs for a project, i.e. delete all existing answers produced for the tasks of a project. This is particularly helpful while developing a new Task Presenter / Project.

I implemented this feature the following way:

modify pybossa/themes/default/templates/applications/task_settings.html by adding a new div:

```
            <div class="row-fluid">
                <div id="task_reset" class="span6 well">
                    <h2><i class="icon-ban-circle"></i> {{_('Reset Tasks')}}</h2>
                    <p>{{_('Reset all the tasks by removing associated answers')}}</p>
                    <a href="{{url_for('app.reset_tasks', short_name=app.short_name)}}" class="btn btn-primary">{{_('Reset')}} <i class="icon-chevron-right"></i></a>
                </div>
            </div>
```

modify pybossa/view/applications.py by adding the following function (inspired by delete_tasks(), not sure if the caching is handled correctly):

```
@blueprint.route('/<short_name>/tasks/reset', methods=['GET', 'POST'])
@login_required
def reset_tasks(short_name):
    """Reset ALL the tasks runs for a given project"""
    (app, owner, n_tasks, n_task_runs,
     overall_progress, last_activity) = app_by_shortname(short_name)
    ensure_authorized_to('read', app)
    ensure_authorized_to('update', app)
    if request.method == 'GET':
        title = app_title(app, "Reset")
        n_volunteers = cached_apps.n_volunteers(app.id)
        n_completed_tasks = cached_apps.n_completed_tasks(app.id)
        app = add_custom_contrib_button_to(app, get_user_id_or_ip())
        return render_template('applications/tasks/reset.html',
                               app=app,
                               owner=owner,
                               n_tasks=n_tasks,
                               n_task_runs=n_task_runs,
                               n_volunteers=n_volunteers,
                               n_completed_tasks=n_completed_tasks,
                               overall_progress=overall_progress,
                               last_activity=last_activity,
                               title=title)
    else:
        task_runs = task_repo.filter_task_runs_by(app_id=app.id)
        task_repo.delete_all(task_runs)
        msg = gettext("All the associated task runs have been deleted")
        flash(msg, 'success')
        cached_apps.delete_last_activity(app.id)
        cached_apps.delete_n_task_runs(app.id)
        cached_apps.delete_overall_progress(app.id)
        return redirect(url_for('.tasks', short_name=app.short_name))
```

add file pybossa/themes/default/templates/applications/tasks/reset.html with following content:

```
{% extends "/base.html" %}
{% set active_page = "applications" %}
{% set active_link  = "settings" %}
{% import "applications/_helpers.html" as helper %}

{% block content %}
<div class="row">
    <div class="span3">
        {{ helper.render_app_local_nav(app, active_link, current_user) }}
    </div>
    <div class="span9">
        <h1><strong>{{app.name}}</strong>: {{ _('Reset all Task Runs') }}</h1>
        <div class="alert alert-danger">
            <strong>{{_('Danger Zone!')}}</strong> {{_('If you delete all task runs associated to the project, they will be gone
            forever!')}}<br/><strong>{{_('You cannot undo this action!')}}</strong>
        </div>
        {{ helper.render_app_summary(app, n_tasks, overall_progress, last_activity, current_user) }}
        <form class="form-horizontal" method="post" action="{{ url_for('app.reset_tasks', short_name = app.short_name) }}">
            <h3><strong>{{_('Are you sure you want to delete ALL the project task runs?')}}</strong></h3>
        <div class="form-actions">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button type="submit" name='btn' class="btn btn-small"
              value="Yes">{{_('Yes')}}</button>
          <a href="{{ url_for('app.settings', short_name = app.short_name) }}"
              class="btn btn-large btn-primary">{{_('No, do not delete
              anything!')}}</a>
        </div>
    </div>
</div>
{{ helper.broken_image() }}
{% endblock %}
```

**Comment by teleyinex** [comment]
Thanks a lot. Actually we should implement this asap in the code ;-)

**Comment by daksh-agarwal** [comment]
I have been following this blog for resetting my counter to zero, but I couldn't find the file pybossa/view/applications.py 
Is there any other way to reset the counter?

**Comment by therealmarv** [comment]
@daksh-agarwal 
`pybossa/view/applications.py` is nowadays `pybossa/view/projects.py`
It has been renamed.

**Comment by daksh-agarwal** [comment]
@therealmarv Thanks! 
I made all the changes as stated above but now even the Settings is now opening.
It is showing in the message: 

"Ooops, Something's wrong
It looks as though we have broken something on our system, sorry

We will try to fix it as soon as we can!"

**Comment by therealmarv** [comment]
@daksh-agarwal 
This is a code error. It seems the code example is not up to date. If you want to implement it yourself check if all methods and variables existing in your codebase. E.g. all `applications` references are `projects` in the newest codebase. Sorry I cannot help you any further at this time.

**Comment by therealmarv** [comment]
If you want to delete all task_runs manually you can also use this approach:
1. Export all tasks to json
2. Delete all tasks with `pbs delete_tasks` and this commandline tool: https://github.com/Scifabric/pbs
3. Reimport the tasks

**Comment by daksh-agarwal** [comment]
@therealmarv  After several runs of different projects, the task counter reached 200. Now, I deleted all the projects, and created a new project. I used image recognition template directly and presented the task. My project counter is now circulating around the same values 201-202. It's not incrementing! 

Tried resetting API key, flushing redis-cli server, but still it's the same. Anything I am missing?

**Comment by daksh-agarwal** [comment]
As per the new code, I expect these changes are required:

**In File pybossa/view/projects.py , add this::**

@blueprint.route('/<short_name>/tasks/reset', methods=['GET', 'POST'])
@login_required
def reset_tasks(short_name):
    """Reset ALL the tasks runs for a given project"""
    (project, owner, n_tasks, n_task_runs,
     overall_progress, last_activity) = project_by_shortname(short_name)
    ensure_authorized_to('read', project)
    ensure_authorized_to('update', project)
    if request.method == 'GET':
        title = project_title(project, "Reset")
        n_volunteers = cached_projects.n_volunteers(project.id)
        n_completed_tasks = cached_projects.n_completed_tasks(project.id)
        project = add_custom_contrib_button_to(project, get_user_id_or_ip())
        return render_template('projects/tasks/reset.html',
                               project=project,
                               owner=owner,
                               n_tasks=n_tasks,
                               n_task_runs=n_task_runs,
                               n_volunteers=n_volunteers,
                               n_completed_tasks=n_completed_tasks,
                               overall_progress=overall_progress,
                               last_activity=last_activity,
                               title=title)
    else:
        task_runs = task_repo.filter_task_runs_by(project_id=project.id)
        task_repo.delete_all(task_runs)
        msg = gettext("All the associated task runs have been deleted")
        flash(msg, 'success')
        cached_projects.delete_last_activity(project.id)
        cached_projects.delete_n_task_runs(project.id)
        cached_projects.delete_overall_progress(project.id)
        return redirect(url_for('.tasks', short_name=project.short_name))


**Add this File at pybossa/themes/default/templates/projects/tasks/reset.html ::**

{% extends "projects/base.html" %}
{% set active_page = "projects" %}
{% set active_link  = "settings" %}
{% set section = _('Reset all task runs') %}
{% import "projects/_helpers.html" as helper %}

{% block projectcontent %}
<div class="row">
    <div class="span3">
        {{ helper.render_project_local_nav(project, active_link, current_user) }}
    </div>
    <div class="span9">
        <h1><strong>{{project.name}}</strong>: {{ _('Reset all Task Runs') }}</h1>
        <div class="alert alert-danger">
            <strong>{{_('Danger Zone!')}}</strong> {{_('If you delete all task runs associated to the project, they will be gone
            forever!')}}<br/><strong>{{_('You cannot undo this action!')}}</strong>
        </div>
        {{ helper.render_project_summary(project, n_tasks, overall_progress, last_activity, current_user) }}
        <form class="form-horizontal" method="post" action="{{ url_for('project.reset_tasks', short_name = project.short_name) }}">
            <h3><strong>{{_('Are you sure you want to delete ALL the project task runs?')}}</strong></h3>
        <div class="form-actions">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button type="submit" name='btn' class="btn btn-sm"
              value="Yes">{{_('Yes')}}</button>
          <a href="{{ url_for('project.settings', short_name = project.short_name) }}"
              class="btn btn-lg btn-primary">{{_('No, do not delete
              anything!')}}</a>
        </div>
    </div>
</div>
{{ helper.broken_image() }}
{% endblock %}


**File pybossa/themes/default/templates/projects/task_settings.html , this needs to be added::**

<div class="row">
  <div id="task_reset" class="col-md-12">
      {{ render_project_card_option(project, upload_method, title=_('Reset Tasks'), explanation=_('Reset all the tasks by removing associated answers'), link=url_for('project.reset_tasks', short_name=project.short_name), link_action_text=_('Reset'), icon='trash')}}
  </div>
</div>

**Comment by daksh-agarwal** [comment]
I expect as per the new repository, these are the changes that needs to be done.

Add this to pybossa/themes/default/templates/projects/task_settings.html

```
<div class="row">
  <div id="task_reset" class="col-md-12">
      {{ render_project_card_option(project, upload_method, title=_('Reset Tasks'), explanation=_('Reset all the tasks by removing associated answers'), link=url_for('project.reset_tasks', short_name=project.short_name), link_action_text=_('Reset'), icon='trash')}}
  </div>
</div>
```


Add this file reset.html at pybossa/themes/default/templates/projects/tasks/ 
```

{% extends "projects/base.html" %}
{% set active_page = "projects" %}
{% set active_link  = "settings" %}
{% set section = _('Reset all task runs') %}
{% import "projects/_helpers.html" as helper %}

{% block projectcontent %}
<div class="row">
    <div class="span3">
        {{ helper.render_project_local_nav(project, active_link, current_user) }}
    </div>
    <div class="span9">
        <h1><strong>{{project.name}}</strong>: {{ _('Reset all Task Runs') }}</h1>
        <div class="alert alert-danger">
            <strong>{{_('Danger Zone!')}}</strong> {{_('If you delete all task runs associated to the project, they will be gone
            forever!')}}<br/><strong>{{_('You cannot undo this action!')}}</strong>
        </div>
        {{ helper.render_project_summary(project, n_tasks, overall_progress, last_activity, current_user) }}
        <form class="form-horizontal" method="post" action="{{ url_for('project.reset_tasks', short_name = project.short_name) }}">
            <h3><strong>{{_('Are you sure you want to delete ALL the project task runs?')}}</strong></h3>
        <div class="form-actions">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button type="submit" name='btn' class="btn btn-sm"
              value="Yes">{{_('Yes')}}</button>
          <a href="{{ url_for('project.settings', short_name = project.short_name) }}"
              class="btn btn-lg btn-primary">{{_('No, do not delete
              anything!')}}</a>
        </div>
    </div>
</div>
{{ helper.broken_image() }}
{% endblock %}

```
Add this to pybossa/view/projects.py:
```

@blueprint.route('/<short_name>/tasks/reset', methods=['GET', 'POST'])
@login_required
def reset_tasks(short_name):
    """Reset ALL the tasks runs for a given project"""
    (project, owner, n_tasks, n_task_runs,
     overall_progress, last_activity) = project_by_shortname(short_name)
    ensure_authorized_to('read', project)
    ensure_authorized_to('update', project)
    if request.method == 'GET':
        title = project_title(project, "Reset")
        n_volunteers = cached_projects.n_volunteers(project.id)
        n_completed_tasks = cached_projects.n_completed_tasks(project.id)
        project = add_custom_contrib_button_to(project, get_user_id_or_ip())
        return render_template('projects/tasks/reset.html',
                               project=project,
                               owner=owner,
                               n_tasks=n_tasks,
                               n_task_runs=n_task_runs,
                               n_volunteers=n_volunteers,
                               n_completed_tasks=n_completed_tasks,
                               overall_progress=overall_progress,
                               last_activity=last_activity,
                               title=title)
    else:
        task_runs = task_repo.filter_task_runs_by(project_id=project.id)
        task_repo.delete_all(task_runs)
        msg = gettext("All the associated task runs have been deleted")
        flash(msg, 'success')
        cached_projects.delete_last_activity(project.id)
        cached_projects.delete_n_task_runs(project.id)
        cached_projects.delete_overall_progress(project.id)
        return redirect(url_for('.tasks', short_name=project.short_name))


```

**Comment by teleyinex** [comment]
This is now implemented as the publishing option for projects. When a project is in draft mode, you can test everything about the project (including webhooks). When you click in publish, the project cleans all the previous tests and puts the project in a state ready for production.
