### ISSUE TITLE
Feature request : Generic edit/verification of locations

### ISSUE THREAD

**Issue by alejandrodob** [Scifabric/pybossa#1089]
Originally posted on PyBossa/crowdcrafting.org#27 by @answerquest:

Hi, kudos to the team who built this platform. I'm not a coder myself, but sharing here a typical requirement for mappers that I think belongs as a generic template like the urban park finder. I realize all of this may not be possible on this platform (or might it??), but anything we can get would be greatly appreciated.

Import a geojson/kml/csv/gpx or similar file having standard point locations with lat/long. (no layering etc.. just simple flat bunch of locations) The systems stores it as the standard geojson.
Turn every location into a task, and list them with the name of the location and lat/long in numbers.
Clicking a task takes you to a map with that item marked, and its previous locations highlighted if any.
Clicking Edit lets you drag the marker to a new spot and save changes. The old location stays visible in a darker color, and is added to the history pile. This map ought to have a search / nominatim facility.
Clicking "thumbs up" or so lets you add an upvote to the currently marked location. (reverted if you press Edit or History)
Clicking "History" shows the previously marked locations and the original one. Choosing one of them and confirming makes it the "current" location, gives it an upvote, removes it from the history pile, and adds the erstwhile current location to the history pile.
The data is stored as geojson, and the previous locations' data, with timestamps and upvotes count, is added in as an array which hopefully won't crash geojson readers. (so after "properties" and "geometry" we have an "oldlocations" or something)
Project owner can browse through all suggested locations for a task, see which has got most upvotes etc, and decide which one to go with finally.
Advantage:
1. The project-starting stage is simplified to just importing a valid mapping file. Meaning real people (whoops, shots fired!) working on public map-related info and not having coding knowledge or the funding to hire expensive coders can make use of this.
2. Upvotes and saving a previous location for reverting bring in a flavor of version-control, and let the project-owner take a call based on inputs received.
3. Possible to generate statistics of distance between original and corrected location, sum of all these distances, variation etc.

**Comment by teleyinex** [comment]
Not implementing right now.
