### ISSUE TITLE
Broken pagination on community page 

### ISSUE THREAD

**Issue by spMohanty** [Scifabric/pybossa#1090]
In the community page `'/account/page/<int:page>'`,
for the pagination, the total number of users is obtained using `pybossa.cache.users.get_total_users()`, and the list of users to show is obtained using `pybossa.cache.users.get_users_page(page, per_page)`.   

`pybossa.cache.users.get_total_users()` uses `User.query.count()` to obtain the **total** number of users, whereas, `pybossa.cache.users.get_users_page(page, per_page)` uses [this SQL query](https://github.com/PyBossa/pybossa/blob/master/pybossa/cache/users.py#L321) to generate the list of users.  [This SQL query](https://github.com/PyBossa/pybossa/blob/master/pybossa/cache/users.py#L321) generates all the users who have submitted **at least one task_run**, hence containing only a subset of the total number of users. 

As the pagination is generated for a subset of users but using the **total number of users** as the maximum users, the pagination links towards the last, return a 404.

**Comment by teleyinex** [comment]
Correct :-) this is an issue. Thanks a lot for fixing it. Can you provide the tests?

**Comment by teleyinex** [comment]
@alejandrodob I think you have fixed this issue right?

**Comment by alejandrodob** [comment]
Nope, it's still broken. I can take this branch and add some tests to the cache function added by @spMohanty if everyone agrees, and then we can merge this changes.
