### ISSUE TITLE
Allow theme writers to define jinja2 custom_filters

### ISSUE THREAD

**Issue by spMohanty** [Scifabric/pybossa#1092]

**Comment by spMohanty** [comment]
The commit https://github.com/spMohanty/pybossa/commit/91d65ff713bc344fe401c7405d96e7872763e081 , will let theme writers independently define their own custom filters in a python file (with a configurable name) in their theme root folder; and then they can use the custom filters all across their template. This makes theme writing much more easier and much more powerful.   
The default filename for defining custom filters is `pybossa_custom_filters.py`, so I could create a file by this name and write into it :
```python 
def pybossa_reverse(s):
	return s[::-1]

def pybossa_md5(s):
	import hashlib
	return hashlib.md5(s).hexdigest()
```

to define two jinja2 custom_filters by the name `pybossa_reverse` and `pybossa_md5` which can now be easily used across all the jinja2 templates by :
```python
{{ "simple_string_example" | pybossa_reverse }}
{{ "simple_string_example" | pybossa_md5 }}
```

**Comment by teleyinex** [comment]
Hi @spMohanty this sounds great, but we need three things for merging it into master:

* [Sign in our contribution guidelines](https://github.com/PyBossa/pybossa/blob/master/CONTRIBUTING.md)
* Provide tests for the code.
* Provide documentation for the new feature

Once you've done that, we can then merge it :-)

**Comment by spMohanty** [comment]
@teleyinex : Sure, I will soon sign and send you the Individual Contributor Assignment Agreement.  For now I have added docs for the feature, but I am a bit confused about how to add a test for this. I would really appreciate some help and/or pointers :)

**Comment by teleyinex** [comment]
We're not supporting this as we're now building a full headless server so anyone can build their own theme/project templates using whatever they want.
