### ISSUE TITLE
two factor authentication in pybossa

### ISSUE THREAD

**Issue by dc1520** [Scifabric/pybossa#1197]
I want to setup a secure login environment for the crowd contributing to the pybossa projects. Is there plug-in or mechanism in place with which two factor authentication can be hooked into pybossa using some existing technologies such as google authenticator or something else? If not, any guidelines on setting up two factor authentication in pybossa would help. Thanks in advance

**Comment by teleyinex** [comment]
As far as I can tell, I don't know. But we've a plugin system, so it should "easy" to develop such a thing :-) 

A quick Google search returns this [library for Python](https://github.com/tadeck/onetimepass) so it should be doable.

We would help you if you start developing it!
