### ISSUE TITLE
Import with CSV URL Importer

### ISSUE THREAD

**Issue by deepjchgit** [Scifabric/pybossa#1222]
I want to import tasks from CSV file that is shared publicly on Amazon S3 storage. I tested that the CSV url is accessible through the web browser. However, when I try to import it using "Import with CSV URL Importer" button, it fails with error "Oops, there is some error in the file" whereas same data when imported through Google spreadsheet, it works. Is there any known issue with "Import with CSV URL Importer". If yes, any workaround? If not, any guidelines to fix this issue at my end. Thanks in advance

**Comment by teleyinex** [comment]
Can you share with us the link to that file? I would like to review what's going on. You can send it to me via daniel@scifabric.com so you don't publicly share it here.

**Comment by dc1520** [comment]
@teleyinex , I emailed you the csv file. The exact error is "(u"Oops! That file doesn't look like the right file.", 'error')" A question. Is there option to upload csv file directly from local file system instead of from a shared location like amazon s3 or dropbox? If yes, please explain how.

**Comment by teleyinex** [comment]
Thanks! I'll take a look. Regarding your question, you can use [pbs](https://github.com/PyBossa/pbs#adding-tasks-to-a-project). It will do it for you easily ;-)

**Comment by teleyinex** [comment]
Do you still have this issue?
