### ISSUE TITLE
Configuration for scheduling task_run zip files download

### ISSUE THREAD

**Issue by dc1520** [Scifabric/pybossa#1235]
This is in continuation to issue #1219 where its mentioned by @therealmarv 

> > > If you run a production PyBossa installation ZIP files are created with RQ scheduler and worker e.g. every hour or day (it is configurable). This RQ scheduler and worker run outside of the PyBossa web application and let PyBossa stay responsive. 

I could not find exact documentation on configuring RQ scheduler to periodically download task_run zip files. I only found this at https://media.readthedocs.org/pdf/pybossa/latest/pybossa.pdf page#82
"Optional is also the RQ scheduler process for speeding up tasks like ZIP creation. This
process is off by default now. If you are developing on RQ worker you want to restart or disable it with supervisorctl"

Off by default is mentioned, but how to turn it on isn't mentioned. If there are specifics on setting up RQ-scheduler for periodic download of zip files, please share. Thanks

**Comment by therealmarv** [comment]
Hi @dc1520 

It is described here in the production setup section of pybossa:
http://docs.pybossa.com/en/latest/nginx.html#configure-rq-scheduler-and-worker-to-run-with-supervisord

The refactoring for ZIP creation on development mode is still on my TO DO list (but not high priority for now). But I think I will have something ready for the very beginning of next year. If you want to refactor the code do not hesitate to send a Pull-Request ;)

Thanks,
Marvin

**Comment by dc1520** [comment]
@therealmarv , the link that you pasted talks about "Configure RQ-Scheduler and -Worker to run with supervisord", but it does not talk specifically about how to enable ZIP file creation of completed tasks with RQ scheduler. Does this means that if I have production setup for pybossa, by default zip files are expected to be created every hour for the newly completed tasks at the end of that hour and no extra settings is required? (Refer the pdf I mentioned in original issue desc, it says option is off by default). Am I missing something?

**Comment by teleyinex** [comment]
In principle by default if you configure the rq-scheduler and worker you should get the ZIP files every done automatically. Is that not working for you?

**Comment by dc1520** [comment]
I have the notification mechanism disabled. In such case, is there any way or user interface through which I can see/find the zip files getting created (if they are)? I have rq-scheduler and worker configured, but unclear about zip files auto creation and how to browse and download them. Do we need to enable auto zip file creation?

**Comment by dc1520** [comment]
@therealmarv, Just wanted to check if you got chance to implement refactoring for ZIP creation as you'd mentioend that it would be ready beginning this year.

**Comment by dc1520** [comment]
@teleyinex, you mentioned that if you configure the rq-scheduler and worker you should get the ZIP files every done automatically. Does this means if rqscheduler and workers are configured, there is no additional configuration/settings required to generate zip files automatically? I guess when you say generating zip files automatically, you meant zip files will be created with newly completed tasks(deleting older zip files) as soon as tasks are completed?Any reference material or steps with which zip files  can be generated automatically will be helpful. Thanks in advance.

**Comment by teleyinex** [comment]
We use the background jobs to take care of that task. Therefore, you need to run them, otherwise it will not be generated automatically. Check the full installation [docs](http://docs.pybossa.com/en/latest/install.html)
