### ISSUE TITLE
Make the API aware of the owner context

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#1258]
Right now the API returns everything even though if you're are registered user and you've your own projects, giving you too much information. The idea is that, the owner of a project is only interested in its own data by default. Therefore, we'll make the API aware of the context.

If an anonymous user access the generic api endpoints like:
- api/task -> it will return all the tasks from the DB as it is doing right now

If a registered user access the generic api endpoint like this:
- api/task -> it will return the tasks that have been created by this user. If there's no tasks created by the user, it will return an empty list. 

We want to keep the possibility to explore the API completely, so for the registered users, there'll be an optional argument in the API endpoint that will enable them to do it:
- api/task?all=true

This argument replicates exactly what PyBossa is doing right now.

**Comment by therealmarv** [comment]
for anonymous the call `api/task?all=true` should also work the same as `api/task`
