### ISSUE TITLE
API to export delta completed task runs since last export

### ISSUE THREAD

**Issue by dc1520** [Scifabric/pybossa#1262]
@teleyinex 
I am using RESTful API to export all completed tasks which is working perfectly fine. This is in the order of, 
1. export all completed tasks : <server>/api/task?state=complete
2. export task_runs for all task id obtained from step #1 : <server>/api/taskrun?task_id=<task_id>

Is there mechanism with which API can exports all completed tasks since last export? Something that can be achieved with client maintaining last export time and passing it as an input param for the next export that API can compare against task completion time that pybossa server is maintaining; API can return task runs with "state" = "completed" and "task completion time" > "last export time"?

**Comment by teleyinex** [comment]
You can use the last_id parameter. Check the [docs](http://docs.pybossa.com/en/latest/api.html?highlight=last_id#list)
