### ISSUE TITLE
user is signed out when changing username/nickname

### ISSUE THREAD

**Issue by jeanphilippegoldman** [Scifabric/pybossa#1295]
in the web interface of pybossa, if a user changes his nick/username in his settings, he is signed out and have to sign in again. i find it a bit unfriendly.... :) 
thanks for your work
j:-P

**Comment by teleyinex** [comment]
This is for security reasons ;-) The user is used for signing the cookie. As it changes, it re-issues a new one, and therefore you have to do the login again :-)
