### ISSUE TITLE
Fix /api/category

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#1306]
There's a bug in the api endpoint category:

{
"status": "failed",
"action": "GET",
"target": "category",
"exception_msg": "Entity '<class 'pybossa.model.category.Category'>' has no property 'owner_id'",
"status_code": 500,
"exception_cls": "InvalidRequestError"
}

**Comment by alexandermendes** [comment]
Also spotted here! https://github.com/PyBossa/pybossa/issues/1298

**Comment by teleyinex** [comment]
Fixed in #1298
