### ISSUE TITLE
SSL Sentry issue

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1308]
I had trouble getting Sentry to work, some kind of SSL issue, see:

```
Unable to reach Sentry log server: <urlopen error [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib> (url: https://sentry.io/api/98766/store/)
```

Upgrading [raven-python](https://github.com/getsentry/raven-python) to the latest version fixed it.

**Comment by teleyinex** [comment]
That's nice :-) We'll update it in the setup.py config file. Thanks! @therealmarv can you fix this issue?

**Comment by teleyinex** [comment]
This is interesting. We just connected Crowdcrafting to Sentry and it worked. We'll investigate it.

**Comment by alexandermendes** [comment]
Can confirm that this also wasn't an issue in our recent PyBossa setup - but you might want to bump up the raven python version anyway (looks like there was some kind of SSL fix in v4.2.0 https://github.com/getsentry/raven-python/blob/master/CHANGES)

**Comment by alexandermendes** [comment]
Still think there might be an issue with <4.2.0 but will close this as it has been open for a year!

**Comment by teleyinex** [comment]
Gosh, I always forget to update this. We have to fix it.

**Comment by alexandermendes** [comment]
Ok, I was just cleaning up some old issues and didn't feel like going back to test on <4.2.0. Could just update anyway, probably not that risky

**Comment by teleyinex** [comment]
:D
