### ISSUE TITLE
Idle user logout

### ISSUE THREAD

**Issue by deepjchgit** [Scifabric/pybossa#1315]
Is it possible to configure idle user logout in Pybossa? Can Pybossa detect a logged in user inactivity and log him/her out after certain time (say 1 hour that is configurable)? If yes, please provide configuration details. If not, any specific reason why this is not part of the system?
@teleyinex

**Comment by dc1520** [comment]
@teleyinex , @therealmarv for logout idle timeout, i guess it can be achieve with something like,
app = Flask(__name__)
app.permanent_session_lifetime = timedelta(minutes=60)
Just wanted to confirm  
1. whether idle user logout can be achieved in pybossa with certain configurations and without any code change?
2. If #1 doesn't apply, is there any reason due to which this two lines of code can not be implemented in pybossa?
3. any better solution that the  two lines of code mentioned above?

**Comment by alexandermendes** [comment]
You can probably add the `PERMANENT_SESSION_LIFETIME ` variable to your settings file (see [Flask-Login docs](http://flask.pocoo.org/docs/0.11/config/#builtin-configuration-values))

**Comment by dc1520** [comment]
@alexandermendes thanks for the reply. The flask documentation says that starting Flask 0.8, we can set integer value to PERMANENT_SESSION_LIFETIME which is in seconds. Hence, I'd set PERMANENT_SESSION_LIFETIME=20 in settings_local.py. However, I do not see user logged out after 20 seconds of inactivity. Am I missing something?

**Comment by dc1520** [comment]
@teleyinex , can pybossa server be configured so that any user who is idle for, say 30 mins(a configurable user session timeout parameter) will be logged out automatically? Or this is not present in pybossa framework at present and need to be developed?

**Comment by teleyinex** [comment]
This should be handled by FlaskLogin: REMEMBER_COOKIE_DURATION	

Check the [docs](https://flask-login.readthedocs.io/en/latest/)

**Comment by dc1520** [comment]
@teleyinex , I set the following under settings_local.py hoping to get user session expire after 2 mins, but user was still logged in. Thoughts?
from datetime import timedelta
REMEMBER_COOKIE_DURATION=timedelta(seconds=120)

**Comment by teleyinex** [comment]
Hi,

Did you deleted first the original cookie? Start from a clean state, and let me know if it works. If this doesn't work, then it's a bug in this library, and I would say you contact directly the people behind Flask-Login ;-)
