### ISSUE TITLE
About 403 'You must request a task first!'

### ISSUE THREAD

**Issue by jimy811111** [Scifabric/pybossa#1318]
Hi,
    After publishing the project,  I try few times to answer the question. However, sometimes there is no response after I send my answer. I check the packages and find that there is a 403 packages and the content says 'You must request a task first!'. Then, it will enter the next question if I click more times. Can I fix that problem? Thanks!
![2016-10-20 5 55 26](https://cloud.githubusercontent.com/assets/6240178/19555200/67d54cf4-96ee-11e6-81e8-942a2af261fe.png)

**Comment by teleyinex** [comment]
Yes, you can only contribute to a project if you request first a task. This is a security measure to avoid problems with robots ;-)
