### ISSUE TITLE
Queries on expected project categories behavior w.r.t. cache updates, project attributes

### ISSUE THREAD

**Issue by dc1520** [Scifabric/pybossa#1326]
What is the expected behavior for a project when it is added/moved to a new category?
1. A project is newly created and added to a new category. Should the project get listed under its category immediately or there could be time delay to update cache? If so, which cache parameter can be tweaked so that the default time delay can be changed so that changes are reflected immediately
2. If the project is password protected, should the project be listed under category? If yes, only to owner/admins or to any user?
3. Project need to be published in order to be listed under its category? If yes, a draft project either without task presenter code or without any tasks in it won't be listed under its category?
4. Is there any limit to number of categories that can be added?
@therealmarv , @alejandrodob

**Comment by teleyinex** [comment]
Hi,

Point 1: In principle, the cache for the given project is purged, and refreshed, so the project will show that information automatically. However, the projects categories will not list it until next refresh of the cache.

Point 2: If I'm not mistaken we show all the projects, the only issue is that it will be required the password.

Point 3: Yes, a project needs to be published. A project can only be published if it has tasks, a template, and it works. We check that within PYBOSSA enabling that option.

Point 4: No, there's no limit.
