### ISSUE TITLE
Task timeout

### ISSUE THREAD

**Issue by dc1520** [Scifabric/pybossa#1327]
Is there any timeout for a task when it is presented to a user? Something like a configurable parameter like TASK_TIMEOUT when set to 15 * 60, the task will be available for submit for 15 mins after user opened a task. In case, user tries to submit answers after 15mins, the submission would fail. Is this related to any existing cache timeout parameter, which when not set will have the default value?

**Comment by teleyinex** [comment]
No, there is no such a thing in PYBOSSA. We have not implemented it because you don't know how much it will take for a given user. This could cause UX problems for users. You can add this to your project creating your own plugin to support this.
