### ISSUE TITLE
Credit Open Knowledge in pybossa.com and crowdcrafting.org footer

### ISSUE THREAD

**Issue by rufuspollock** [Scifabric/pybossa#1328]
*Apologies if this is the wrong place to post but i looked for a website repo for pybossa.com or crowdcrafting.org before heading here.*

Given original contribution of Open Knowledge (and myself) to original versions of Pybossa and Crowdcrafting it would be nice to have a credit in the footer. 

This used to be there e.g. http://web.archive.org/web/20140402040235/http://pybossa.com/

You can grab Open Knowledge's logo from https://okfn.org/press/resources/

**Comment by teleyinex** [comment]
Hi Rufus,

We've had always a link to your site in the Repository, in our [Acknowledgements section](https://github.com/Scifabric/pybossa#acknowledgments), as you have been and will be part of PYBOSSA always.

However, we have updated the footers to have only our brands, as it helps us to deliver our message. 

We've added you also to the About page in Crowdcrafting (PYBOSSA does not have one), so you are fully recognized everywhere.

All the best,

Daniel
