### ISSUE TITLE
Combining Pybossa with Enki

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1359]
I am trying to integrate Pybossa with Enki so that analysis can be done in real-time. I have found that Webhooks can be used for this. But, how exactly this can be done?

**Comment by RockyCD** [comment]
Dude, it is literally right here[They go step by step](https://github.com/Scifabric/enki) and then follow this  [see below](https://github.com/Scifabric/webhooks)

Installation

To install the project all you need is run the following command (we recommend you to use a virtual environment):

pip install -r requirements.txt
Now, copy the settings.py.template file to: settings.py and fill in the information. Once you are done with this file, you'll be ready to run the server.

NOTE: Be sure to have a PyBossa API-KEY as the analysis will be stored in the PyBossa results table.

NOTE: It requires a PyBossa server >= 1.2.0.

Running the server

Now that you've the required libraries installed, running the server is as simple as this:

python app.py
Configuring background jobs

By default, this project has disabled the creation of queues in your system. If you expect to have lots of contributions in your project, we recommend you to enable them.

To support queues you will need to install in your machine a Redis server. Then, change the flag: enable_background_jobs to True in your settings.py file, and restart the server.

Note: if you are already running a Redis server and queues, you can customize the name of your queue in the settings file. Check out the config variable: queue_name.

Running the background jobs

Now that you have the project running background jobs, you need to process them. This is very simple, in another terminal run the following command:

rqworker mywebhooks
NOTE: If you've changed the name of the queue, please, update the previous command with your new queue name. That's all! Enjoy!!!

**Comment by daksh-agarwal** [comment]
@RockyCD thanks for that info. 
I have a doubt. For the GET request to run on webhooks, there should be some trigger from the Pybossa server. Do I need to add the GET request code anywhere in my Pybossa code? Or, in other way, how exactly it is handled?

**Comment by teleyinex** [comment]
Closing this issue, as I've answered it in another one.
