### ISSUE TITLE
Installing Juju inside Vagrant on a Server in AWS EC2

### ISSUE THREAD

**Issue by RockyCD** [Scifabric/pybossa#1360]
##### SOLVED
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ juju bootstrap
Bootstrapping environment "local"
Starting new instance for initial state server
Building tools to upload (1.25.6.1-trusty-i386)
Installing Juju agent on bootstrap instance
Logging to /home/vagrant/.juju/local/cloud-init-output.log on remote host
Installing package: curl
Installing package: cpu-checker
Installing package: bridge-utils
Installing package: rsyslog-gnutls
Installing package: cloud-utils
Installing package: cloud-image-utils
Installing package: tmux
Bootstrapping Juju machine agent
Starting Juju machine agent (juju-agent-vagrant-local)
Bootstrap agent installed
local -> local
Waiting for API to become available
Waiting for API to become available
Waiting for API to become available
Bootstrap complete
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ 

It just took a very long time about 30 minutes .
________________________________________________________________________________
This is my third try at installing pybossa. I shall admit that I know very little about configuring web-servers and have spent almost 14 hours going through the guides online.

I have learned a hell of alot about sqlalchemy, redis, juju, and postrgres.

I am not giving up yet.

## I currently am trying to configure pybossa with juju on a server on AWS that is virtualized 
"Ubuntu Server 14-04 LTS -HVM--14-04 LTS"
 
I have followed everything step by step
Everything was going fine until this

`juju init`
juju switch local`
juju bootstrap`

For some reason I am stuck after I type in `juju bootstrap`
```
 vagrant@vagrant-ubuntu-trusty-32:/vagrant$ juju bootstrap
Bootstrapping environment "local"
Starting new instance for initial state server
Building tools to upload (1.25.6.1-trusty-i386)
Installing Juju agent on bootstrap instance
```

It has been hanging for about 20 minutes now.

I know that is was local

`vagrant@vagrant-ubuntu-trusty-32:/vagrant$ juju switch`
local
`vagrant@vagrant-ubuntu-trusty-32:/vagrant$ cat ~/.juju/current-environment`
local

**Comment by therealmarv** [comment]
my advice:
Do not use the Juju and Vagrant setup for AWS EC2.
Please follow manual steps [here](http://docs.pybossa.com/en/latest/install.html) and [here for server installing](http://docs.pybossa.com/en/latest/nginx.html).

Thank you. I will close this issue.
