### ISSUE TITLE
New blueprint routes not directing through uwsgi

### ISSUE THREAD

**Issue by Lythimus** [Scifabric/pybossa#1449]
I've created some new routes which serve properly when running directly from run.py, but not when running PyBossa through uwsgi. I'm getting a nginx 404 error when serving through uwsgi. Is there something additional which must be done to add pages to PyBossa? Do I need to manually run register_blueprint for all new paths?

**Comment by therealmarv** [comment]
Do you have a small example code for checking that? When it runs in run.py it should also run in uwsgi (this is my experience but I could be wrong).

**Comment by teleyinex** [comment]
As @therealmarv says, it should run the same. There's no difference actually.

**Comment by Lythimus** [comment]
I'm not positive what you mean by example code, but here are some of my configuration files and one of the functions with blueprint routing:

**Comment by Lythimus** [comment]
I attempted many work-arounds for this without much luck, but eventually tried changing the blueprint.route to see if that would cause a configuration update and it worked, but changing it back caused the same 404 error. The route isn't used twice anywhere. So I'm going to chalk this up to some strange hash collision or an nginx problem. I'm fine with changing the route though, so I'll just leave it as something else. Thanks for your input.
