### ISSUE TITLE
Enable project creation only by admin

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1461]
I have been working on Pybossa on my localhost for a while. I created a project and published it. Then, asked my friends to work on the tasks, hosting it via tunneling. One of my friends created his own experiment while working on my experiment. Now, for the next user, Pybossa shows two published projects. After targeted 10 runs of the project, I observed that only 3 people contributed to my project! 

I need to disable this feature so that only I (admin) have the permission to create the project and blocking others from project creation. Is that possible?  If yes, then how?
 
TIA.

**Comment by teleyinex** [comment]
Hi,

It's not possible right now, via the settings file, but you can "solve it" modifying the theme and allowing only to access the creation of projects to admins. We'll add this feature asap as we think is pretty useful.

Cheers
