### ISSUE TITLE
Dashboard rendering

### ISSUE THREAD

**Issue by portableant** [Scifabric/pybossa#1472]
Hello,
This is probably quite a simple one, I upgraded the @micropasts platform to the latest pybossa distribution and moved it to EC2 and the one thing I am having problems with is rendering the dashboard. It works as soon as the cache is cleared and rq-scheduler/worker/pybossa restarts and then suddenly stops and produced this in the error log:
`pybossa.core:ERROR:[2017-03-01 00:00:10,471] 'dict object' has no attribute 'info' [in /var/www/pybossa/pybossa/view/admin.py:410]`
I've upgraded db etc. Just wondered if there was a step I have overlooked before digging deeper.
Dan

**Comment by teleyinex** [comment]
Hi,

Which DB are you running? Because the Admin Dashboard uses Materialized views, and it needs PostgreSQL>=9.3.

In any case,  the error from line 410 is strange as it is in the current master branch where we return the dict with the response. Are you running the very last version of the code?

Cheers

**Comment by portableant** [comment]
Hi Daniel,
`pybossa=# SELECT version();
                                                   version                                                    
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.3.16 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit
(1 row)`

I'm running on AWS EC2, nginx and uswgi configured and I'm on this commit from your pybossa repo f12609f33c8c21b81c4d73e47cc46bc67b80079a 
Dan

**Comment by portableant** [comment]
Daniel,
I've reinstalled the virtual environment and system and now everything works fine, same architecture etc. So I am closing this issue.  
Dan

**Comment by teleyinex** [comment]
Great to know that it was just a problem with the virtualenv ;-)
