### ISSUE TITLE
Increasing taskruns limit in API

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1475]
As per [http://docs.pybossa.com/en/latest/api.html](url) link of the documentation, we can limit the task runs to max of 100.

By default PYBOSSA limits the list of items to 20. If you want to get more items, use the keyword limit=N with N being a number to get that amount. There is a maximum of 100 to the limit keyword, so if you try to get more items at once it won’t work.
 
But, I need to increase the limit further to 200. How can I do this?

**Comment by teleyinex** [comment]
If you need to get more that 200 domain objects per API call, then you will need to modify the source code, or if you prefer, build a plugin. We use 100 as it's pretty standard ;-)
