### ISSUE TITLE
Get current user id through API

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1484]
Is there a way to get the current user id of the person who is contributing on the tasks, through the Pybossa API?

**Comment by teleyinex** [comment]
Can you elaborate a bit your question? You can get the task runs from a user like this

api/taskrun?user_id=15 -> it will return all task runs from that user ID

If you want to know the user_id before hand, then, no, you cannot. This is done on purpose to avoid fraud with task runs. This is really important, as you might end up having results from trolls or spammers.

**Comment by daksh-agarwal** [comment]
Suppose I am one of the contributor for a project. I register on the Pybossa and contribute on the tasks. After this, I want to get my task-run information, and I don't know my user-id. Is there a way to get my task-run details, through the API? By going through api/taskrun, I get a lot of information of all the users, but I want to see just mine information.

**Comment by teleyinex** [comment]
Good case :-) and yes, you are covered.

Use JSON mimetype for the request and go to this endpoint: http://server/account/user.name/ That should return all your data in JSON. NOTE: you need to be logged in, and you can only get your own ID, not from others.

**Comment by daksh-agarwal** [comment]
By JSON mimetype, doesn't it mean this: 
```
$.ajax({
    beforeSend: function(xhrObj){
        xhrObj.setRequestHeader("Content-Type","application/json");
    },
    type: "GET",
    url: 'http://server/account/user.name/',       
    dataType: "json",
    success: function(json){
       console.log('username',json);
    }
});
```

Also tried this:
```
var userinfo;
var xhr_user = new XMLHttpRequest();
var user_url = 'http://server/account/user.name/';
xhr_user.open('GET', user_url,false);
xhr_user.onload = function(e1) {
	var status_user = xhr_user.status;
	userinfo=JSON.stringify(xhr_user.responseText);	
	}
xhr_user.send(null);
```

But unfortunately both of them didn't return anything!

**Comment by munterkalmsteiner** [comment]
> Good case :-) and yes, you are covered.
> 
> Use JSON mimetype for the request and go to this endpoint: http://server/account/user.name/ That should return all your data in JSON. NOTE: you need to be logged in, and you can only get your own ID, not from others.
> 
> You need the latest version of PYBOSSA for this to work ;-)

Yes, this works if I know the username in advance. However, how do I use this for example in a task presenter? I don't know the username at this point, or?

**Comment by munterkalmsteiner** [comment]
> > Good case :-) and yes, you are covered.
> > Use JSON mimetype for the request and go to this endpoint: http://server/account/user.name/ That should return all your data in JSON. NOTE: you need to be logged in, and you can only get your own ID, not from others.
> > You need the latest version of PYBOSSA for this to work ;-)
> 
> Yes, this works if I know the username in advance. However, how do I use this for example in a task presenter? I don't know the username at this point, or?

... and solved it immediately after stating the question:
```
$.ajax({
type: "GET",
url: "/account/profile",
contentType: "application/json",
dataType: "json",
success: function(data) {
  console.log(data.user.id);
},
error: function (xhr, textStatus, errorThrown) {
  console.log(xhr.responseText);
}
});
```

**Comment by teleyinex** [comment]
Exactly :-)
