### ISSUE TITLE
Average contribution time

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1489]
I've just noticed a strange problem where a few task run rows are throwing off my project's average contribution time. So, to demonstrate, this query:

```sql
SELECT (to_timestamp(finish_time, 'YYYY-MM-DD-THH24-MI-SS.US') - to_timestamp(created, 'YYYY-MM-DD-THH24-MI-SS.US')) AS average_time, finish_time, created   
FROM task_run
WHERE project_id=39 
GROUP BY finish_time, created;
```

Gives this:

|       average_time    |                 finish_time                   |                  created                         |
|--------------------|--------------------------------|---------------------------------|
| 00:01:54.684934   | 2016-09-27T10:07:50.765732 | 2016-09-27T10:05:56.080798   |
| -09:57:03.836929 | 2016-09-27T10:02:34.772813  | 2016-09-27T09:59:38.609742  |
| 00:01:46.275159    | 2016-09-26T13:18:25.011009  | 2016-09-26T13:16:38.735850   |

If got a few rows like this, always where the finish time was at 10am and the created time at 9am. I'll try to figure this out myself but leaving it here until I do, or perhaps someone else has some ideas!

**Comment by teleyinex** [comment]
So the created time is updated for the task run [here](https://github.com/Scifabric/pybossa/blob/e0bbf9b1489c50234f678909ff04593f4cfeb62d/pybossa/api/task_run.py#L85) Basically, when a user requests a task, we use that information for marking it as when it was created.

Then the finish time is generated when it's saved in the DB. Thus, the issue could be in the previous code.

**Comment by teleyinex** [comment]
A possible idea: could it be that someone from the same IP requested the same task? Then, there could be a variation on the finish create time, and therefore create this issue. Do you know if those tasks were contributed by anonymous users? Can you check?

**Comment by alexandermendes** [comment]
They actually all happen to come from logged in users. I only have 10 rows where this has happened. It's probably not a coincidence that they all happen at similar times but I have no idea what this means!

```
   average_time   |        finish_time         |          created           | user_ip | user_id
------------------+----------------------------+----------------------------+---------+---------
 -09:30:47.421042 | 2017-02-04T10:27:37.944555 | 2017-02-04T09:58:25.365597 |         |     354
 -09:56:16.675608 | 2017-02-25T20:02:53.769125 | 2017-02-25T19:59:10.444733 |         |      91
 -09:45:35.657555 | 2017-03-18T20:02:54.569655 | 2017-03-18T19:48:30.227210 |         |     355
 -09:38:32.22632  | 2017-02-04T10:17:50.007771 | 2017-02-04T09:56:22.234091 |         |     354
 -09:56:52.609739 | 2017-02-25T20:00:46.475059 | 2017-02-25T19:57:39.084798 |         |      91
 -09:57:03.836929 | 2016-09-27T10:02:34.772813 | 2016-09-27T09:59:38.609742 |         |     287
 -09:42:25.787918 | 2017-03-18T20:08:19.009068 | 2017-03-18T19:50:44.796986 |         |     355
 -09:44:57.424581 | 2017-02-11T20:01:25.447232 | 2017-02-11T19:46:22.871813 |         |     355
 -09:44:29.895109 | 2017-02-11T20:02:50.403481 | 2017-02-11T19:47:20.298590 |         |     355
 -09:57:17.67046  | 2016-09-27T10:01:01.196234 | 2016-09-27T09:58:18.866694 |         |     287
``` 

:thinking:

**Comment by alexandermendes** [comment]
Oops, didn't mean to close (although we possibly can soon but may as well figure it out first)

**Comment by teleyinex** [comment]
so, the date object (strings) look fine. Interestingly it's the computation that looks wrong.

**Comment by teleyinex** [comment]
```python
created = datetime.datetime.strptime('2017-02-04T09:58:25.365597', '%Y-%m-%dT%H:%M:%S.%f')
finished = datetime.datetime.strptime('2017-02-04T10:27:37.944555', '%Y-%m-%dT%H:%M:%S.%f')
(finished - created).seconds/60
```
That returns 29 minutes. Which is the right answer, so PYBOSSA is saving the info properly. Could it be the SQL doing it wrong?

**Comment by teleyinex** [comment]
WAIT! In your code you have: 

SELECT (to_timestamp(finish_time, 'YYYY-MM-DD-THH24**-**MI**-**SS.US') - to_timestamp(created, 'YYYY-MM-DD-THH24**-**MI**-**SS.US'))

That **-** dash should be **:** correct?

**Comment by alexandermendes** [comment]
I still get the same result, but you're right that the SQL must be somehow wrong as the finish time does come after the created time (I was going blind and thought it didn't). I need to go back and remind myself of why I thought this was a problem in the first place!

**Comment by alexandermendes** [comment]
Ok, it was something to do with the "T" in the middle of the string, I think. This returns the right result.

```
SELECT (to_timestamp(finish_time, 'YYYY-MM-DD"T"HH24:MI:SS"Z"') - to_timestamp(created, 'YYYY-MM-DD"T"HH24:MI:SS"Z"')) AS average_time, finish_time, created   
FROM task_run
WHERE project_id=39 AND (to_timestamp(finish_time, 'YYYY-MM-DD"T"HH24:MI:SS"Z"') < to_timestamp(created, 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
GROUP BY finish_time, created;
```

**Comment by alexandermendes** [comment]
Can't remember why I thought of this in the first place but maybe I was doing something wrong in my templates and came to the wrong conclusion. We can close it for now!

**Comment by teleyinex** [comment]
Great! Well, at least now we know what happened :D
