### ISSUE TITLE
Deployment: Invalid user name pybossa in section 'program:pybossa'

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1517]
While deployment, I am facing this issue with the supervisor.  It returned this error. 

supervisor.service - Supervisor process control system for UNIX
   Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-03-28 17:21:52 IST; 30s ago
     Docs: http://supervisord.org
  Process: 6553 ExecStop=/usr/local/bin/supervisorctl $OPTIONS shutdown (code=exited, status=203/EXEC)
  Process: 6551 ExecStart=/usr/local/bin/supervisord -n -c /etc/supervisor/supervisord.conf (code=exited, status=203/EXEC)
 Main PID: 6551 (code=exited, status=203/EXEC)

Mar 28 17:21:52 home systemd[1]: supervisor.service: Unit entered failed state.
Mar 28 17:21:52 home systemd[1]: supervisor.service: Failed with result 'exit-code'.

On further analysis, it returned me this error:
Error: Invalid user name pybossa in section 'program:pybossa' (file: '/etc/supervisor/conf.d/pybossa.conf')

Do I need to change the name to something else? If yes, what would it be to deploy it on server?

**Comment by teleyinex** [comment]
It looks like you don't have the user pybossa in the system. Please, check the official documentation of supervisor for this issue.
