### ISSUE TITLE
Allow admins to update results

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1530]
Hi, so I'm sure you had a reason for this but do you think it would make sense to allow admins, as well as project owners, to update results? Admins or owners are allowed to update a project and it's tasks but not the results, which seems a bit disconnected. The main reason that I need to make it easier to set up something centrally to process webhooks for projects that may have different owners. Can submit a PR if you think this sounds reasonable!

**Comment by teleyinex** [comment]
We only allow results to be tweaked by the owners, as it's something "personal" but you are 100% right that's a bit disconnected. Thus, send us your PR and we will merge it. It makes sense, specially because we allow admins to handle USER domain objects as well via the API.

**Comment by alexandermendes** [comment]
Cool, thanks. I'll get that done this week.

**Comment by alexandermendes** [comment]
Just went to finally do this and noticed you already fixed it in https://github.com/Scifabric/pybossa/issues/1724! 👍
