### ISSUE TITLE
Add Flask-Webpack

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1534]
What do you think about adding [Flask-Webpack](https://github.com/nickjj/flask-webpack) as a requirement, allowing us to bundle assets with webpack (which gives more options that webassets - although perhaps they could both stay there to give alternative options)?

**Comment by teleyinex** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10219683-264929344_5-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by alexandermendes** [comment]
I actually only started looking at it yesterday but it looks pretty straightforward. So it can just take a manifest file produced with something like [this](https://www.npmjs.com/package/webpack-manifest-plugin) and then lets you access those paths in the templates. I could have a quick go locally and see how it goes!

**Comment by teleyinex** [comment]
Nice. We use VueJS now for almost all our new code on the frontend, so this will be the perfect mix :-D

**Comment by teleyinex** [comment]
Quick thing. I just forgot to mention that you don't need flask-webpack. You can build now your fully SPA with any mix of webpack + Js framework of your choice as all the important endpoints support JSON. Check out this: http://docs.pybossa.com/en/latest/api.html#pybossa-endpoints Also, pybossa-pbs can be used with your webpack :-) And we have some themes that are using webpack (not on the server side) as we compile it.

**Comment by alexandermendes** [comment]
Oh yeah, I did notice all of the new JSON stuff, which is really cool but unfortunately I had already started work on a new theme and don't have time to go back and rebuild using a new framework (maybe for the next project though :wink:). Of course, I can still bundle stuff with webpack but I then face an issue with caching and I can't see another way of getting the the hashed asset names into my templates. There probably are alternatives but this looks like one pretty straightforward solution that it might still be handy to have as an option.

**Comment by teleyinex** [comment]
Sure! We've solved it using the webpack html plugin, and forcing it to write the template file that we want to build with webpack. It works, and it is pretty simple. But, as you say, we should provide also both things as well :D

**Comment by alexandermendes** [comment]
Ok so I'm actually moving towards using the html webpack plugin to generate my base templates too. Flask-Webpack seems a bit messy to setup. So, it seemed like a good idea at the time but you can probably close this if you like!

**Comment by teleyinex** [comment]
Perfect then. The solution works really well. So closing this in just in case.
