### ISSUE TITLE
Help: single sign-on coupled with drupal

### ISSUE THREAD

**Issue by aborruso** [Scifabric/pybossa#1537]
Hi,
I'm building a drupal website and I want to integrate inside it a pybossa project.

I would like to have a single sign-on for both. Is there already a way to do it? Someone has had some experience on it?

Thank you

**Comment by teleyinex** [comment]
Hi,

PYBOSSA has a plugin system, so you will be able to build that customization. Right now, as far as we know, no one has implemented such a thing. 

Just in case. PYBOSSA supports External User IDs, allowing services like Drupal (or any other project) to integrate PYBOSSA without having to use SSO. Basically when requesting a task or sending a task_run you will identify your DB users via the External User ID. More info here: http://docs.pybossa.com/en/latest/api.html?highlight=uid#using-your-own-user-database

**Comment by aborruso** [comment]
Hi @teleyinex for now, only thank you very much!

I will write a note here when done.
