### ISSUE TITLE
Expose global template context via the API

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1543]
Have just started trying to rebuild our theme with Vue using your new JSON endpoints and am wondering how to access the current user. Would it be worth exposing the [global template context](https://github.com/Scifabric/pybossa/blob/master/pybossa/core.py#L562-L579) via the API?

I can't really see any other way of getting to these when attempting to write a front end that only communicates with PyBossa via the API (although it is entirely possible that I'm missing something)!

**Comment by alexandermendes** [comment]
So the above probably isn't the solution, just trying to figure out how to establish if there is a user currently signed in, via the API. I see that `/account/project` will return `"not_signed_in"` if this is not the case, so perhaps that's the way to handle it.

**Comment by teleyinex** [comment]
PYBOSSA uses cookies for sessions, so when a user authenticates via the server/account/signin endpoint (using JSON) you will get the cookie. The cookie sets the user name as the first parameter, so you can read it and therefore get it from there.

Another solution (if you don't want to use cookies) is to use the Session Storage. Use a very basic template. The base template will inject via JS the user data using the SessionStorage. This ensures that all your other endpoints will work fine, as the session will be available to them via that. 

We've used both approaches in several places. What do you think?

**Comment by alexandermendes** [comment]
Cool ok, so I think I'll probably store the user details using vuex, but will go and play around with various options. Thanks for the speedy reply! :smile:

**Comment by teleyinex** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9936649-264929344_5-s1-v1.png?transparent=1&palette=1&width=246)
