### ISSUE TITLE
Uploader allows us to upload .css or a .js file as the avatar

### ISSUE THREAD

**Issue by 97amarnathk** [Scifabric/pybossa#1560]

**Comment by teleyinex** [comment]
Hi,

Great catch! Is this happening in the Projects, Account or in both?

**Comment by 97amarnathk** [comment]
Hi Daniel,

This is in both.

Also, I am new to the open source world. Can I be allowed to contribute to
it. I have identified the problem.

Regards,
Amarnath

**Comment by teleyinex** [comment]
Yes, please, send the patch. You just need to check the file [Contributing][https://github.com/Scifabric/pybossa/blob/master/CONTRIBUTING.md) and we'll merge it :-)
