### ISSUE TITLE
Error in rebuilding the database

### ISSUE THREAD

**Issue by Saket-Karve** [Scifabric/pybossa#1563]
Rebuilding the database produces an error as it cannot drop tables which have some foreign key relation in some other table.
Instead of using DROP TABLE, DROP CASCADE should be used.
`python cli.py db_rebuild` produces this error.

**Comment by teleyinex** [comment]
Can you submit the patch? We would merge it :-)

**Comment by Saket-Karve** [comment]
Sure!

**Comment by sfluo** [comment]
Is the patch ready? Run into this problem ...

**Comment by teleyinex** [comment]
Hi,

@Saket-Karve has never sent the patch, but you can easily delete the DB using SQL. Just access postgresql and use:

drop database pybossa;

Done! We use this all the time :-)

**Comment by sfluo** [comment]
not familiar with psql at all. but how to delete?

Try to do, it says connection refused.
$ dropdb -h 127.0.0.1 -i -e pybossa

**Comment by therealmarv** [comment]
@sfluo If you use the regular Ubuntu installation this are the steps:

```bash
su postgres
psql
```

then in psql delete database and recreate
```sql
drop database pybossa;
create database pybossa owner pybossa encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;
\q
```
