### ISSUE TITLE
NoneType overall progress

### ISSUE THREAD

**Issue by therealmarv** [Scifabric/pybossa#1567]
I think this should be fixed without any non pushed hotfixes ?!

![image](https://user-images.githubusercontent.com/1050582/27388477-e64a792a-569b-11e7-9217-94ef66582de6.png)

**Comment by teleyinex** [comment]
Fixed here: https://github.com/Scifabric/pybossa/commit/367017445dc84f43d7fdc161769409f18ead1ff3
