### ISSUE TITLE
After a project is deleted, it may still show its broken link under the Contributions section.

### ISSUE THREAD

**Issue by 97amarnathk** [Scifabric/pybossa#1580]
After a project is deleted, Its link (broken link) is still seen in under the User Contribution if he has contributed to the project. Either remove the Project entirely from contributions or remove the link and keep it as plain text.

**Comment by teleyinex** [comment]
Yes, that's due to the caching thing. We have an issue related about how to delete the projects (that we should fix at some point). Basically, good catch!  We're not refreshing the data properly.
