### ISSUE TITLE
Install by hand does not specify how can I choose redis database for PyBossa

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Scifabric/pybossa#1584]
I have existing Redis databases, so I wonder how it is possible to configure PyBossa or sentinel  to choose unused Redis DB for PyBossa.

The guide I'm following is: http://docs.pybossa.com/en/latest/install.html

I couldn't find any place in current codebase where this could be added.  It seems to me that config is taken directly from Sentinel (https://github.com/Scifabric/pybossa/blob/master/pybossa/core.py#L308), but I couldn't find in the sentinel documentation how to do it.

**Comment by therealmarv** [comment]
PYBOSSA itself is dependent on Sentinel. It's not talking directly to Redis except the RQ Scheduler which needs a direct connection to a redis master for scheduling tasks.

So you need to configure Sentinel to use at least one master (and optional several slaves) according to https://redis.io/topics/sentinel

## You need to configure Sentinel and Redis DB in 2 places

To let e.g. run several PYBOSSAs run with the same sentinel and redis network you need only to seperate the redis DB number (here it is number `2`).

Sentinel is on IP 10.0.0.2 in this example and redis master runs on IP 10.0.0.1 here.

### PYBOSSA `settings_local.py`

Here an excerpt of `settings_local.py` for specifying a Sentinel node and it should use Redis DB 2 with mymaster master redis DB with key prefix `foobar` in this example

```ini
## Cache setup. By default it is enabled
## Redis Sentinel
# List of Sentinel servers (IP, port)
REDIS_CACHE_ENABLED = True
REDIS_SENTINEL = [('10.0.0.2', 26379)]
REDIS_MASTER = 'mymaster'
REDIS_KEYPREFIX = 'foobar'
REDIS_DB = 2
```

### Supervisor `/etc/supervisor/conf.d/rq-scheduler-foobar.conf`

You also need to change rq-scheduler supervisor script. In this example it is also using Redis DB 2 for saving:

```ini
[program:rq-scheduler-foobar]
command=/home/foobar/pybossa/env/bin/rqscheduler --host 10.0.0.1 --port 6379 --interval 60 --db 2
directory=/home/foobar/pybossa
autostart=true
autorestart=true
priority=998
user=foobar
log_stdout=true
log_stderr=true
logfile=/var/log/rq-scheduler-foobar.log
logfile_maxbytes=10MB
logfile_backups=2
```

**Comment by therealmarv** [comment]
I will close this issue for now, but I made a mark for myself that this information is missing in the docs (because it's a special case).

**Comment by KrzysztofMadejski** [comment]
Thank  you!
