### ISSUE TITLE
Please update your e-mail address in your profile page, right now it is empty!

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Scifabric/pybossa#1586]
But it's not empty, I have a valid email specified.

I have a fresh install and created a user specifying all the fields.

**Comment by therealmarv** [comment]
Will look into this. Thx!

**Comment by therealmarv** [comment]
I was able to reproduce the bug today if username=email address.

**Comment by teleyinex** [comment]
Fixed in #1597
