### ISSUE TITLE
Add optional orderby parameter for category projects

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1593]
When retrieving projects via the API (e.g. [/project/category/featured/](http://docs.pybossa.com/en/latest/api.html#project-category-featured)), or otherwise, it would be nice to be able to order projects by `n_tasks`, `overall_progress` etc. Then we can provide better sorting options for the user - "Closest to completion", "Most help needed" etc. This can be done in the browser but only for the projects actually visible on that page (not page 2, 3 etc.).

So maybe using [`rank(projects)`](https://github.com/Scifabric/pybossa/blob/master/pybossa/util.py#L395-L413) as the default but with an option to pass an `orderby` param to the various `/category/<shortname>` endpoints.

I can have a go at this when I find a bit of time!

**Comment by teleyinex** [comment]
This is great idea :-)
