### ISSUE TITLE
Completed project, missing task runs in exporter.

### ISSUE THREAD

**Issue by mittagessen** [Scifabric/pybossa#1599]
I've built a transcription template based project for pybossa and the first project has been finished. There are 599 tasks in the project but using the task_run exporter only 36 results are contained in the JSON file (42 in the CSV). When I use the "Browse Tasks" interface I can manually get the results for every single one of the 599 but that is obviously not nearly as efficient as just downloading everything at once.

**Comment by teleyinex** [comment]
Which version of PYBOSSA server are you running?

**Comment by mittagessen** [comment]
We're running on commit ``44b550f169808f40a1a4d76971011016fe764fd0``. I realize it is a bit old but I couldn't find anything in the history about task run exporter fixes and am not entirely sure if just doing a upgrade to the current HEAD is trouble-free.

**Comment by teleyinex** [comment]
In principle it's trouble free :-) but we highly recommend you to do a backup.

We've improved the exporter not so long ago, so yes, you would need to use it :D Just in case, are you running the background jobs?

**Comment by mittagessen** [comment]
They should run, although the RQ frontend lists no tasks right now. I'll try upgrading and reopen the ticket if that doesn't resolve the issue.
