### ISSUE TITLE
Regarding golden tasks

### ISSUE THREAD

**Issue by baibinghere** [Scifabric/pybossa#1600]
Hi,

I'm testing pybossa from a server I built from instruction [Installing PYBOSSA by hand](http://docs.pybossa.com/en/latest/install.html#). 
I noticed that in FAQ it mentions a concept of golden(_calibration_) task. I'm curious that where can I use this feature from web browser?
When I import tasks, I don't see where I can mark a task as a golden task, not to mention the follow up features like setting weight of certain tasks for certain users.
Is this something we have to manually set into the pybossa database task table?

Thanks!

**Comment by teleyinex** [comment]
Hi,

Golden tasks can only be set via the API. You only need to update a task (or when you create it) to set to true the field: [calibration](https://github.com/Scifabric/pybossa/blob/master/pybossa/model/task.py#L46).

Regarding weight or priority: you can do that as well via the API, or via the web. Just go to your project, find the Tasks section, enter into the task settings, and there you will see the task priority settings area.

**Comment by teleyinex** [comment]
Just opened a [ticket](https://github.com/Scifabric/pbs/issues/42) in our command line tool, to enable you to use it as well from it.
