### ISSUE TITLE
Deleting a project failed

### ISSUE THREAD

**Issue by baibinghere** [Scifabric/pybossa#1601]
Hi,

I've tried to delete a project and it gives me the below error:
You do not have the permission to access the requested resource. It is either read-protected or not readable by the server.

But my account is actually both administrator and owner of the project.
From the code in pybossa/auth/project.py, I see the below code:

```
def _delete(self, user, project):
    if self.result_repo.get_by(project_id=project.id):
        return False
    return self._only_admin_or_owner(user, project)
```
self.result_repo.get_by(project_id=project.id) got result so the function returned false.
I'm not sure what does this line means? But the fact that project not able to be deleted should be an issue.

Also, I'm wondering, if there's tasks/results/blogs under Project, can we delete the project along with all the data (tasks/results/blogs...)?

When I delete tasks, I see only the tasks that has not run been deleted. How to clean up all the tasks and task results?

**Comment by teleyinex** [comment]
Did you published the project? By default, PYBOSSA does not allow deleting published projects, for a reason. Let me explain.

A PYBOSSA project could get thousands of contributors from all over the world. These contributors, contribute for free, so their work should remain there for others to see (and use) as this is an open source technology and open data project. The issue: if a project owner with bad intentions, completes the project, downloads all the data and deletes it, then, the volunteers will get nothing back (neither the community). For this reason, we added this "counter-measure".

If you are the admin, however, I guess you will have access to the DB. In that case, just unpublish the project (just change the published field into false), and then from the PYBOSSA project delete it as usual.

NOTE: we've a small issue with big projects (thousands of tasks) when a project is going to be deleted. We want to fix this asap.

**Comment by baibinghere** [comment]
Uh, now I get it!
The code there is to check if there's task_run been answered by the user...
You made a good point! Thanks!

**Comment by BonarBeavis** [comment]
This makes it quite difficult to do functional tests with pybossa. This really should be an opt in for the admin.

**Comment by teleyinex** [comment]
Yes, but you can do all the tests without publishing the project. It behaves the same. What's the problem about this?

**Comment by BonarBeavis** [comment]
The check is not if a project is published, but if a result exists. So when I want to test the result webhook, I can not delete the project anymore. My workaround right now is, that I remove the check in the sources of my Pybossa installation. Maybe a error message, which gives a feedback why it is not possible to delete the project, would be helpful.

**Comment by teleyinex** [comment]
Can you try with unpublishing your project? Because you should be able to test everything, including webhooks, without publishing a project. If this happens, then, this is a bug.
