### ISSUE TITLE
REDIS_CACHE_ENABLED does not seem to work

### ISSUE THREAD

**Issue by baibinghere** [Scifabric/pybossa#1604]
Even though I set `REDIS_CACHE_ENABLED = False`, I'm still getting data from the redis.
Looks like I have to set something like below into the settinngs_local.py:
```
import os
os.environ.setdefault('PYBOSSA_REDIS_CACHE_DISABLED', "FALSE")
```

Could you please confirm if this is an issue?

**Comment by teleyinex** [comment]
We would need to test. We use it in all of our servers and with our clients, so we haven't not fully tested without it (except in the tests itself). Can you run a REDIS FLUSH ALL and see if you still get the cache populated?

**Comment by baibinghere** [comment]
I'm bringing this up because I did a global search in pybossa project and I didn't see `REDIS_CACHE_ENABLED` been used.
However, I see `PYBOSSA_REDIS_CACHE_DISABLED` been defined in `with_cache_disabled ` decorator.

**Comment by baibinghere** [comment]
Another proof is that in http://docs.pybossa.com/en/latest/customizing.html
we see the below text:
Disabling the Cache
If you want to disable the cache, you only have to export the following env variable:

```PYBOSSA_REDIS_CACHE_DISABLED='1'```

However, in both default_settings.py and settings_local.py, we got:

```REDIS_CACHE_ENABLED = True```

**Comment by teleyinex** [comment]
Good catch :-) We need to fix this asap.

**Comment by teleyinex** [comment]
This is the line where it's checked for DISABLED

https://github.com/Scifabric/pybossa/blob/master/pybossa/cache/__init__.py#L83

**Comment by teleyinex** [comment]
This variable should be renamed:

https://github.com/Scifabric/pybossa/blob/master/pybossa/default_settings.py#L60

**Comment by teleyinex** [comment]
If the tests pass, we can merge it. In principle, by removing those variables it's fixed, as they only added confusion. Now, it should be more clear ;-)

**Comment by teleyinex** [comment]
By the way:

![bitmoji](https://render.bitstrips.com/v2/cpanel/7638212-264929344_5-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by baibinghere** [comment]
You are welcome :-)
Thanks for your quick response!
