### ISSUE TITLE
Using pybossa other language does NOT work

### ISSUE THREAD

**Issue by baibinghere** [Scifabric/pybossa#1607]
Below is the content of babel.cfg
[python: themes/pybossa-default-theme/**.py]
[jinja2: themes/pybossa-default-theme/**/templates/**.html]
[jinja2: themes/pybossa-default-theme/templates/home/_pybossa_text.html]
extensions=jinja2.ext.autoescape,jinja2.ext.with_

However, the folder name has changed from pybossa-default-theme to default, so I guess the folders should be:
[python: themes/default/**.py]
[jinja2: themes/default/**/templates/**.html]
[jinja2: themes/default/templates/home/_pybossa_text.html]
extensions=jinja2.ext.autoescape,jinja2.ext.with_

Also, there's no *.py files under themes/default/ anymore, does this mean we don't need to translate *.py files anymore?

Thanks!

**Comment by baibinghere** [comment]
Attach the document link:
http://docs.pybossa.com/en/latest/translating.html

**Comment by teleyinex** [comment]
That's for when we compile it. The default-theme comes with the po and mo files, so you don't need it. Be sure to clone --recursive the pybossa repository, or  you will not get the theme and also the translations.

Finally, be sure that you run the command of this [section](http://docs.pybossa.com/en/latest/translating.html#enabling-multiple-locales). Otherwise, PYBOSSA will not find the translations.

**Comment by baibinghere** [comment]
Hi, teleyinex,

I did do the above operations. 
If I'm not using --recursive, I believe I cannot even start the server.

I'm sorry the title is not correct. I can actually switch to other languages.
The problem is about adding new strings to the translation.
**

> Updating translation and adding new strings to the translation

**

It requires to execute the below command
```
$ cd pybossa
$ pybabel extract . -F translations/../babel.cfg -k lazy_gettext -o translations/messages.pot
```
When I execute it, it always give me a message.pot without any translation script.
I checked the babel.cfg it seems to specify the wrong folder names.

Could you please check?
