### ISSUE TITLE
Full text search broken for projects

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1622]
For the rest we get, for example:

```
{"status": "failed", "action": "GET", "target": "project", "exception_msg": "'ProjectRepository' object has no attribute 'language'", "status_code": 415, "exception_cls": "AttributeError"}
```

**Comment by alexandermendes** [comment]
I'll try to address this in https://github.com/Scifabric/pybossa/pull/1621, as I need to fix the tests there anyway.

**Comment by alexandermendes** [comment]
Ok, I guess it's just the project endpoint, strange

**Comment by teleyinex** [comment]
I know this is bug, because I've fixed it recently for the helping materials API endpoint. Do you need a hand?
