### ISSUE TITLE
Caching issue on category items listing?

### ISSUE THREAD

**Issue by mialondon** [Scifabric/pybossa#1628]
The screenshots show the same item, once as a featured item and once under a category heading. In one case, a description that was updated, and the number of contributors and percentage complete has been updated; in the other, it hasn't. Are 'featured items' cached?

![cached description progress markers playbills_libcrowds_com_contribute](https://user-images.githubusercontent.com/380763/29464239-34bdde1c-842d-11e7-8347-a071c9ffae9c.png)
![live description progress markers playbills_libcrowds_com_contribute](https://user-images.githubusercontent.com/380763/29464240-34c295ce-842d-11e7-9bb8-6774357aaa1f.png)

**Comment by alexandermendes** [comment]
Ok, so `cached_projects.get_all_featured()` uses `STATS_FRONTPAGE_TIMEOUT` and so `cached_projects.get_all()` uses `APP_TIMEOUT` (i.e. 12 hours for the first and 15 mins for the second, by default). We can change these in our theme but maybe the default ought to be changed too?

**Comment by teleyinex** [comment]
I think so :D We should align those, so we see all the time the same :dagger: 

NOTE: we have a higher timeout for stats front page, because that page will be accessed by many more people than the others, so having the cached for a longer time will have less impact on the DB. In any case, I agree that we should align them, and then allow people to choose whatever they want.

What do you think @alexandermendes and @mialondon?

**Comment by mialondon** [comment]
@teleyinex if they have to be different to save the database, maybe an hour would better reflect progress than 12 hours?

**Comment by teleyinex** [comment]
Totally :D

**Comment by alexandermendes** [comment]
This could still of course result in the same project showing 0% complete in one place and 90% in the other (hopefully :smile:), so they should both use the same timeout, say `APP_TIMEOUT`, which I guess could be increased?

Also noticed that `get_all_featured()` seems to be missing the `front_page_featured_projects` key prefix, so it's not cleared when the cached categories are reset.

**Comment by alexandermendes** [comment]
So you can close this now. We'll upgrade the 2.8.0 soon.
