### ISSUE TITLE
Import data from FTP and HTTP listings

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Scifabric/pybossa#1631]
I'd like to create importer for data stored on FTP and HTTP listings. Should I do it as a pull-request to the core pybossa with files under [pybossa/importers](https://github.com/Scifabric/pybossa/tree/master/pybossa/importers) or should it be a separate plugin?

**Comment by teleyinex** [comment]
As a PR please :D This should be in the core system!

**Comment by KrzysztofMadejski** [comment]
Working prototype for FTP import. Now I have to clean that, add HTTP import, add tree chooser to S3.

![ftp-import](https://user-images.githubusercontent.com/849975/31290702-ba02f8de-aacd-11e7-832f-0f15360e60dc.png)

**Comment by teleyinex** [comment]
Wow so cool! Looking forward to the tests so we can merge it. Quick thing: we're redoing the docs, as the current system is far from optimal. The docs will go [here](https://github.com/Scifabric/docs.pybossa.com) Thus, before you add the docs, let us know so we can add it to the new theme and system.
