### ISSUE TITLE
Escaped html markup in flash messages

### ISSUE THREAD

**Issue by fiorda** [Scifabric/pybossa#1633]
Hello, I'm seeing this issue in some of the flash messages containing html markup:

<img width="1035" alt="screen shot 2017-08-24 at 11 14 53 am" src="https://user-images.githubusercontent.com/4744443/29673932-adee42aa-88be-11e7-9415-669181618ec8.png">

<img width="1033" alt="screen shot 2017-08-24 at 11 15 24 am" src="https://user-images.githubusercontent.com/4744443/29673935-b1fbbb7a-88be-11e7-867c-80858b5f5d1f.png">

<img width="1034" alt="screen shot 2017-08-24 at 11 15 57 am" src="https://user-images.githubusercontent.com/4744443/29673941-b6ec3f4c-88be-11e7-8c30-3384d8fb7f9f.png">

as also noted in https://github.com/Scifabric/pybossa/issues/1585, should the html be wrapped in a `Markup` object? I tested it and it fixes the issue.

**Comment by teleyinex** [comment]
we should fix this asap.

**Comment by fiorda** [comment]
I created https://github.com/Scifabric/pybossa/pull/1634 for it, let me know if you think it's appropriate

**Comment by teleyinex** [comment]
So cool! Thanks a lot.
