### ISSUE TITLE
Broken translation strings

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Scifabric/pybossa#1636]
I would like to raise an issue I see with creating translation strings. Translation strings should be translatable as whole sentences or whole phrases. 

Breaking it in the middle, in order to add html styling, input variable, etc. results in broken pieces that are hard or impossible to translate. Hard because context is lost, impossible potentially if translated language is read right-to-left or in other cases or the same word is used in different contexts and conjugated for example.

### Example 1
https://github.com/Scifabric/pybossa-default-theme/blob/master/templates/projects/task_autoimport_options.html#L16-L17
```html
<p>{{_('Use one of the following available')}}
<strong>{{_('importers')}}</strong> {{_('to import tasks...')}}</p>
```
could be written as
```html
<p>{{_('Use one of the following available %(strongs)simporters%(stronge)s to import tasks...')|format(strongs='<strong>',stronge='</strong>)}}</p>

<!-- or a bit more clear using trans -->

<p>{% trans strongs='<strong>',stronge='</strong>' %}Use one of the following available {{strongs}}importers{{stronge}} to import tasks...{% endtrans %}</p>

<!-- or just in this case trust/check translators not to loose styling -->

<p>{% trans %}Use one of the following available <strong>importers</strong> to import tasks...{% endtrans %}</p>
```

### Example 2
https://github.com/Scifabric/pybossa-default-theme/blob/master/templates/projects/importers/s3.html#L16
```html
{{_('For more information, please look at')}} <a href="http://docs.pybossa.com/en/latest/user/overview.html#importing-the-tasks-from-an-amazon-s3-bucket" target="_blank">{{_('the documentation')}}.</a>
```
could be written as
```html
{% trans link='<a href="http://docs.pybossa.com/en/latest/user/overview.html#importing-the-tasks-from-an-amazon-s3-bucket"  target="_blank">', _link='</a>' %}For more information, please look at {{link}}the documentation{{ _link }}{% endtrans %}
```

**Comment by teleyinex** [comment]
I think we might be moving away from Flask-Babel as PYBOSSA is now a full headless server. This means, that translations could be decoupled as well, and run within a full Single Page App. What do you think?

**Comment by KrzysztofMadejski** [comment]
So are you dropping the whole interface around crowdcrafting?

If you go for headless server and deletes all the frontend then this issue looses its relevance. Translations should go with frontend whether it will be Single Page App or whichever other solution.

**Comment by teleyinex** [comment]
Not yet. We're transitioning towards this, so we can keep both at the moment.

**Comment by KrzysztofMadejski** [comment]
I'd be interested in maintaining crowdcrafting afterwards. Meaning: as a SAAS solution for PyBossa, not neccessarily the domain, etc.
