### ISSUE TITLE
Oauth logins are problematic for SPAs

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1647]
I'm not sure what the solution is here but the Oauth signups/logins (for Facebook, Twitter etc.) are problematic when running PyBossa as a headless backend, due to the way in which users are redirected back to different backend URLs depending on the outcome of the attempted signin. So, to `account.update` if the email needs updating or `account.signin` if it fails, and so on.

Perhaps we need a setting (OAUTH_EXTERNAL_REDIRECT or whatever) to redirect back to a separate frontend server, perhaps also sending back some JSON with the result so that the frontend can deal with it as required.

**Comment by alexandermendes** [comment]
Or perhaps this will be a similar solution to https://github.com/Scifabric/pybossa/issues/1646

**Comment by teleyinex** [comment]
I think the last ;-) But you are right, as we'll have two different endpoints in different servers, the frontend will catch the Oauth info, and send it to the current server. According to people from [Auth0](https://stackoverflow.com/questions/21451172/how-to-integrate-oauth-with-a-single-page-application) a redirect should work. Can you try with your http server to redirect from the spa to the backend API of PYBOSSA and see if it works?

**Comment by alexandermendes** [comment]
Yeah so I can redirect to the `/facebook`, `/twitter` endpoints and trigger the normal Oauth flow and all of that works. The problem is when this finishes and we end up back at something like this:

https://github.com/Scifabric/pybossa/blob/master/pybossa/view/twitter.py#L120-L141

Here the user's browser can now be redirected to various backend places, where we really want them to be sent back to our frontend instead.

**Comment by teleyinex** [comment]
Oh, I see! Here we're missing our [redirect_content_type](https://github.com/Scifabric/pybossa/blob/master/pybossa/util.py#L114) so it returns the page the front end should render for the user. Would that work? Because you will get in the front end the next URL that the user is expecting to get, so you will be able to trigger it via your routing mechanism. What do you think?

**Comment by alexandermendes** [comment]
Yeah I noticed that, although I'm not sure if it will work once the user has been directed away from the site then sent back, as we'll no longer know that the original request was a JSON one...

Maybe we need to pass an additional parameter with the callback to the `/oauth_authorized` endpoints (say `server=my.frontend.server`).

It's a tricky one!

**Comment by teleyinex** [comment]
Maybe we can then add a new flag for PYBOSSA that will ensure that OAUTH only returns JSON for Twitter, Facebook and Google endpoints, ensuring that this will not happen. This makes total sense because it will not allow users to register using the default api endpoints, correct?

**Comment by alexandermendes** [comment]
It could be a solution but not sure that I entirely understand it as the user actually leaves the site entirely to login to twitter (or wherever), then comes back to oauth-authorized where the user management stuff is handled. Not saying it's wrong just I can't see how it works yet!

Another solution (or maybe part of the solution) would be to just always respect the `next` query param. So the user login from my frontend works fine if I send this - the redirects happen and, if this was successful and no emails need to be updated etc we end up back at this `next` url. It's when we start sending users to a range of pages that it gets complicated. I'll have a quick test locally now anyway!

**Comment by teleyinex** [comment]
Now I get it. Let me know how it goes with it, and then we can find a solution. There should be a way. Another possible solution could be to store the next URL in the localStorage of the user, so once the user has been logged in, a redirect happens by the front end. What do you think?

**Comment by alexandermendes** [comment]
Cool, so just spotted your new `SPA_SERVER_NAME` flag. I think we might want to just use this (if present) to redirect the user to their servers versions of newsletter_subscribe, forgot_password, signin etc.

I guess we lose a little flexibility here in terms of the endpoints that the frontend must implement but otherwise it seems like quite a clean solution.

Also, this should be another issue if I'm right, but I think `SPA_SERVER_NAME` should also be used for the registration confirmation email links!

**Comment by teleyinex** [comment]
You're 100% right! We should add it there as well!

**Comment by alexandermendes** [comment]
Ok so this seems to work! https://github.com/Scifabric/pybossa/pull/1652

Maybe I should add a couple of tests though
