### ISSUE TITLE
Add custom emails For SPAs

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1653]
The emails used to be defined as templates in the Flask themes, I think we need a new solution for SPAs.

**Comment by teleyinex** [comment]
Yes, but this is not a big problem as you can install the default theme, fork it, update the templates, and the new SPAs config variable will handle everything. We're using it like this with a client, so I don't see where it is the problem. Please, explain it a bit more as I'm sure I'm missing something ;-)

**Comment by teleyinex** [comment]
@alexandermendes any update on this?

**Comment by alexandermendes** [comment]
Yeah I meant to get back to this one, I suppose the only sensible way is to modify the backend theme. It's just that we currently don't have to touch this at all so was trying to avoid doing so only for the emails. I'll have a quick think and probably close this by the end of the day.

**Comment by teleyinex** [comment]
OK! No rush ;-)

**Comment by alexandermendes** [comment]
Sorry for the delqy on this one. Closing as I guess there is no other way to do it

**Comment by teleyinex** [comment]
We can always move that part to a specific folder within PYBOSSA code, BUT, I think we will end up with the same issue, as you will want to have your templates, language, etc.

**Comment by alexandermendes** [comment]
Hmm, actually how about some kind of a "send_mail" webhook? Could be really simple to set up, just take the same dict that's passed to the current send_mail method and add a MAIL_WEBHOOK setting to tell it where to go. That could make things a bit more flexible.
