### ISSUE TITLE
Delay in fully processing changes made through the web interface

### ISSUE THREAD

**Issue by cyplas** [Scifabric/pybossa#1661]
Certain setting changes made in the interface aren't fully processed right away, but with a large delay. And there isn't any feedback to that effect, so the impression is that the feature doesn't work, or even worse, breaks something. One reproducible example (at least on our installation):

1. Open project with short name = foo.
2. Under Settings -> Project details, set the short name = foox.
3. The project URL is now http://.../project/foox with short name = foox, but I can also still visit http://.../project/foo (where the short name is still foo), so it looks like the project has been duplicated, not renamed.
4. Only after about 15 minutes (according to my last test), http://.../project/foo finally shows "Page not found!"

There are other setting changes that also take some time to be processed. Daniel has suggested that it is a problem of the cache not being cleaned when it should.

**Comment by teleyinex** [comment]
This is because of the caching not being cleaned properly. We are investigating this issue. Thanks for the report.

**Comment by teleyinex** [comment]
When using the API the cache is not updated, so the changes do not propagate accordingly. Also, when using the pybossa projects view, the cache is not always cleaned, missing some important updates.
