### ISSUE TITLE
Plugin listing in documentation

### ISSUE THREAD

**Issue by BonarBeavis** [Scifabric/pybossa#1671]
I can not find a list of plugins in the documentation. Is my google-fu failing me?

**Comment by teleyinex** [comment]
There's not such a list yet. The British Library has created several plugins for PYBOSSA:

https://github.com/alexandermendes/pybossa-discourse
https://github.com/alexandermendes/pybossa-gravatar

Also, there might be a few more developed by others, so we usually search on Github as well.
