### ISSUE TITLE
Google OAuth endpoint breaks when next param passed

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1672]
Took me a while to track this one down and I still don't quite understand it, but passing `next=whatever` to the `/google` endpoint essentially causes:

```
TypeError: prepare_grant_uri() got multiple values for keyword argument 'response_type'
  File "flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "pybossa/view/google.py", line 47, in login
    _external=True))
  File "flask_oauthlib/client.py", line 524, in authorize
    **params
  File "oauthlib/oauth2/rfc6749/clients/web_application.py", line 86, in prepare_request_uri
    redirect_uri=redirect_uri, scope=scope, state=state, **kwargs)
```

So `response_type` is obviously added [here](https://github.com/Scifabric/pybossa/blob/919b8db80721d67b63631a6cc8a356f1c078af3e/pybossa/view/google.py#L37-L50), but I think it also gets stored in the session by Flask-OAuth [here](https://github.com/mitsuhiko/flask-oauth/blob/d5c3f6a229df1c3566b9bc3233311c109b4dcff9/flask_oauth.py#L338-L348), so we end up with a duplicate.

Again, not sure about that but there's definitely some kind of issue there.

**Comment by alexandermendes** [comment]
To cut a long story short - this seems to be fixed by removing [`response_type`](https://github.com/Scifabric/pybossa/blob/919b8db80721d67b63631a6cc8a356f1c078af3e/pybossa/view/google.py#L44)

**Comment by alexandermendes** [comment]
Note that you can also see the same issue on crowdcrafting. The above should do it (pending tests, of course).

**Comment by teleyinex** [comment]
Wow, really good catch. We should add the tests and fix it ;-)

**Comment by alexandermendes** [comment]
Done!
