### ISSUE TITLE
redirect_content_type doesn't work when uploading images

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1676]
As stated in the docs, when uploading images via the API (at `/account/<name>/update` and `/project/<short_name>/update`) we can't sent the content type to JSON. I finally managed to get image uploads working via the API but at each of those endpoints, as we're using [handle_content_type](https://github.com/Scifabric/pybossa/blob/167577773a7308df03e1b611509d86f0ed52c5bb/pybossa/util.py#L63), we don't get the correct response back. Ideally we would still get a JSON response back, with any flash messages etc. Not sure about the solution yet but I guess we need some fix there!

**Comment by teleyinex** [comment]
The issue has been the following, when you upload an image you have to setup the content type to multipart form. This does not allowed us to identify if you were coming from an SPA or a regular form. The solution I think is to have an argument like this:

/account/<name>/update?format=json <- will return the output as JSON while if we don't include that argument it will return regular HTML. What do you think?

**Comment by alexandermendes** [comment]
Cool yep, sounds good to me!

**Comment by alexandermendes** [comment]
I think we have a similar issue with the OAuth redirects. When redirecting back to the SPA after authorisation we don't know that a JSON response should be returned, so we lose the feedback from flash messages etc. 

Perhaps a generic option here would work? Say `response_format=json` that can be added to any of these routes that involve redirects to force a JSON response where for whatever reason setting the Content-Type doesn't work? I thin OAuth and image uploads are the only scenarios for now but I guess you might have more in future.
