### ISSUE TITLE
S3 Import UX

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Scifabric/pybossa#1680]
It would be good to add following improvements to the S3 import

3. "Import" button should be disabled at start or even not existing. Now if one sets bucket name and clicks Import one will get a message "IT LOOKS LIKE THERE WERE NO NEW RECORDS TO IMPORT" even if there are files in the bucket. How should I know that first I should click "Search"
2. "Search in a bucket" button should be highlighted, now it looks like its disabled
1. A message informing "Please choose files to import" should be shown after clicking "Search in a bucket"
2. There should be an option to Select all files

Nice to have:
- it would be cool to have an option to select/deselect all files in a given folder

![import-s3](https://user-images.githubusercontent.com/849975/31027159-7d8773a0-a549-11e7-9595-b65269507ad2.png)

**Comment by KrzysztofMadejski** [comment]
I was wondering about implementing library, such as https://www.abeautifulsite.net/jquery-file-tree , for showing files to import. Would it be possible regarding your licensing terms (that you expect everyone to sign contributor's agreement)?

**Comment by teleyinex** [comment]
Everything sounds more than reasonable :-) Go for it. Regarding the licensing, as you have already signed the contribution agreement, you can work on it and include the outside libraries that you want. If it's someone from your organization, then, if you signed the Entity Agreement, just send the PR from your organization from Github and you will be covered as well.

**Comment by teleyinex** [comment]
We're also using less and less jQuery in favor of pure Javascript where possible. Would it fine to use libraries like this instead of jQuery plugins for building this? Check out this library https://www.npmjs.com/package/tree-view

**Comment by KrzysztofMadejski** [comment]
The library that you've mentioned is based on React. Is it a better dependency than jquery? Do you use React already on the frontend?

**Comment by teleyinex** [comment]
Gosh, that's bad. We use Vuejs. What I meant is that we would love to use, if possible, full JS libraries, instead of jQuery ones. If that's not possible, then, we will adapt :-)
