### ISSUE TITLE
Add custom project contrib button to /projects/category endpoints

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1686]
Can you see anything that would get in the way of adding the custom project contrib button to the `/projects/category` endpoints?

It's mainly from here (and the home page) that we're linking people to the project presenters. It would be really useful if we could block people from clicking on the 'Contribute' button once they have completed all tasks etc.

**Comment by teleyinex** [comment]
With the new JSON endpoints, you can build that button yourself and forget about what PYBOSSA is providing. Yesterday I was thinking about probably deleting this feature now that we're moving towards a full headless solution. You could use the values of the progress of the project to show or hide that button yourself without relying on PYBOSSA contrib button. What do you think?

**Comment by alexandermendes** [comment]
Cool ok, I was wondering about this too. So, that obviously works for projects that are actually completed but not for those where the user has completed all tasks but the project is still open? Unless we make a call to attempt to get new tasks for all listed projects, but that seems expensive!

**Comment by teleyinex** [comment]
Do you know about the new ?participated argument for the api/task endpoint? It handles everything for you :-)

**Comment by teleyinex** [comment]
http://docs.pybossa.com/en/latest/api.html?highlight=participated#excluding-contributed-tasks-from-get-queries

**Comment by alexandermendes** [comment]
Oh yeah, I did spot that at some point but must've forgotten, very nice :smile: 

So along with a param to filter a list of project IDs this should do the job, thanks!
