### ISSUE TITLE
Problem with Boolean form fields submitted via the API

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1692]
We seem to have a problem submitting boolean fields, like `allow_anonymous_contributors`, via the API. Below is what we get on the PYBOSSA server at https://github.com/Scifabric/pybossa/blob/4924dd094af4b89a099d87ca5d63c81a70446911/pybossa/view/projects.py#L424

**request.data:**
```
{  
   "allow_anonymous_contributors":false,
   "category_id":14,
   "csrf":"1507222159.91##f553a2fc756ff8f9c9492c2225b7822c977e97b0",
   "description":"Mark up the titles of plays in historic playbills for later transcription",
   "errors":{},
   "id":66,
   "long_description":"",
   "name":"Mark Titles: Miscellaneous Plymouth theatres 1796-1882 (Vol. 2)",
   "password":null,
   "protect":false,
   "short_name":"identify_titles_miscellaneous_plymouth_theatres_1796-1882_vol_2",
   "webhook":""
}
```

**form.allow_anonymous_contributors.__dict__:**
```
{  
   'errors':[  

   ],
   'description':u'',
   'short_name':'allow_anonymous_contributors',
   'default':None,
   'data':True,
   '_translations':<flask_wtf.i18n.Translations object at 0x7fc67b9ddd90>,
   'process_errors':[  

   ],
   'label':Label('allow_anonymous_contributors', lu'Allow Anonymous Contributors'),
   'flags':   <wtforms.fields.Flags:{  

   }   >,
   'filters':(),
   'validators':[  

   ],
   ' 
raw_data':[  
      False
   ],
   'object_data':None,
   'type':'BooleanField',
   'id':'allow_anonymous_contributors',
   'name':'allow_anonymous_contributors'
}
```

**print form.allow_anonymous_contributors.data**
```
True
```

**Comment by alexandermendes** [comment]
So we submit `allow_anonymous_contributors: false` and the `raw_data` of the form successfully gets updated to `False`, but the `data` doesn't - so we get left with `True`, meaning that these fields can't be updated via the API.

**Comment by teleyinex** [comment]
Yes, this is an issue I've seen before. Specially using different frontend frameworks, as the checkbox can be set with a value like "on" "off" instead of "true" "false". Also, we should have something like this: https://github.com/Scifabric/pybossa/blob/master/pybossa/util.py#L479 to avoid these issues.

**Comment by teleyinex** [comment]
Basically, we have to use that function when importing the data from form.data.field
