### ISSUE TITLE
Fix 'Announcement' has no attribute 'project_id' API error

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1694]
I've been getting this from the announcements API endpoint:

```
{  
   "status":"failed",
   "action":"GET",
   "target":"announcement",
   "exception_msg":"type object 'Announcement' has no attribute 'project_id'",
   "status_code":415,
   "exception_cls":"AttributeError"
}
```

We've seen in before (https://github.com/Scifabric/pybossa/issues/1298), just need to delete the owner_id

**Comment by teleyinex** [comment]
This is because you're using the form instead of the API, correct?

**Comment by alexandermendes** [comment]
Nope, that was via the API. In fact, you can see it here:

https://backend.libcrowds.com/api/announcement

**Comment by alexandermendes** [comment]
I think this is fixed now, closing
