### ISSUE TITLE
Clean cache after PUT requests for all domain objects

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1697]
So I noticed you just fixed the cleaning of the cache after updating a project via the API (https://github.com/Scifabric/pybossa/pull/1688). Now I've just come across the same thing with users. I'm adding an extra field to the user.info but this puts the object out of line with the user retrieved from `/profile`. Probably a similar solution needed, and I guess it will eventually come up for all domain objects!

**Comment by teleyinex** [comment]
Yes, yes! I wanted to do it first for projects, as much of the complains were coming from there. As you will see in the code, I've created in the API a caching object that can be easily extended. Please, go ahead and add it as well!

**Comment by teleyinex** [comment]
Also, I've invited you to the Gitter channel. It would be really nice to have you there, so we can chat in real time :D

**Comment by alexandermendes** [comment]
Cool, see you there 😄
