### ISSUE TITLE
Can not get the results

### ISSUE THREAD

**Issue by chunweixu** [Scifabric/pybossa#1711]
I use the demo of flickrperson, but I can not get the results after I have completed the task and I  have no idea to solve it. Please give me some help?
![screen shot 2017-10-18 at 1 26 56 am](https://user-images.githubusercontent.com/12983441/31681461-e9e9eb9e-b33c-11e7-9646-71bd7baaca30.png)
![screen shot 2017-10-18 at 1 27 33 am](https://user-images.githubusercontent.com/12983441/31681482-f230a96e-b33c-11e7-8f00-5590f0329bf2.png)

**Comment by teleyinex** [comment]
I would say that's because you are not running in the background the jobs for generating the ZIP files. Are you running our last PYBOSSA version? 2.8.0?

**Comment by chunweixu** [comment]
Yes, I install PYBOSSA following the official site (http://docs.pybossa.com/install/). And I use the flickrperson demo to test my PYBOSSA. But it fails to get results.

**Comment by teleyinex** [comment]
OK, can you set in the settings_loca.py file the LOG flag to a file, replicate the error and post here the output of the log file? That would help us to debug it.

**Comment by Algorithm-zhangkai** [comment]
I also have the same question about it. When a task has been executed by user (more than redundancy),it doesn't show anything in results.

**Comment by teleyinex** [comment]
Hi, we released a fix (see #1753) that should address this issue. Have you tried with the latest version of PYBOSSA in master?
