### ISSUE TITLE
Add fields to domain objects retrieved via standard API routes

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1712]
As we get ready to launch our first full SPA, and depart further from logic laid down before PyBossa enabled this, it would be great to add in a few fields to the domain objects returned via the API. For example, one of the things I need to do now is retrieve all featured projects that are also in a particular category, and be able to show the overall progress etc. of those projects. So, I'm currently thinking of adding things like `n_tasks`, `category_id` and the `featured` flag for projects returned via `/api/project`. I know you see this already but having maximum flexibility here would really help in future!

**Comment by alexandermendes** [comment]
Oh, of course category_id is already there, but you get the idea 😉

**Comment by teleyinex** [comment]
Yes, we've had this week a conversation @therealmarv and I about making the API calls more equal :D I like this idea, so submit a PR.

**Comment by alexandermendes** [comment]
Ah so now that you've got a separate project stats table I guess the easy solution is to just expose that via the API, say at `/api/projectstats` (a bit like `/api/globalstats`) and allow that to also be queried using a list of project ids.

**Comment by alexandermendes** [comment]
Oh, nope, that table is just used to cache the stats for the past 2 weeks (I think), will do something else!

**Comment by alexandermendes** [comment]
Decided to go with the repository model used for your other domain object so that we can take advantage of all of the work already done for sorting, searching by multiple IDs etc.

**Comment by teleyinex** [comment]
So cool! Loving it so far!
