### ISSUE TITLE
Improve handling of unauthorised API requests

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1717]
I think JSON requests should return a 401 response where user signin may be required, rather than sending back the response for the signup page. The frontend can then be responsible for implementing the logic. 

This seems much cleaner than checking every response on the client, see if it was a redirect and figure out what this redirect means (e.g. check if the redirect is to specifically to `/account/signin`).

**Comment by teleyinex** [comment]
That sounds good actually.
