### ISSUE TITLE
Add tags table for more flexibility in organising projects

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1720]
What do you think about adding a basic tags/labels table so that projects can be grouped, and therefore searched, according to more flexible criteria. It's difficult to decide sometimes how to group things - so, in our new frontend we currently have projects grouped by volume, but they could equally be grouped by location, or type of task (transcribe, mark up etc.). The API is getting ever more flexible and it would be really cool if we could use something like [this](https://monterail.github.io/vue-multiselect/) to tag our projects and then allow people to filter via multiple tags.

Tags could be read by all but only created/updated/deleted by admins (new tags could be suggested via a forum or something, but that's outside of the scope of this). Tags wouldn't be linked to a particular category and could we even just start with say `id`, `name` and `info` (maybe a `hex` field for a custom colour would be cool, although it can go in the info otherwise). Happy to submit a PR but obviously want to see what you think first!

**Comment by teleyinex** [comment]
Hi,

We've discussed this a lot. We have never implemented them because usually, tags have a terrible impact regarding performance at the DB level. However, now that we're entirely using PostgreSQL Arrays, it might be easier to add tags in such a way. Also, we discussed yesterday moving towards JSONB, and this would be the perfect match for that, as we would not need to add a new column, just use the project.info field and search within it.

What do you think about moving to JSONB and use it there?

**Comment by alexandermendes** [comment]
It would indeed be really cool to somehow expose the JSONB operators via the API. Further down the line we would actually want to use this for many other reasons, search as searching without our nested JSON results. I guess you already have some plans on how to implement this then?

**Comment by teleyinex** [comment]
Yes, more or less :D We would use something similar to our info=key::value for = SQL queries. We can create our own valid URL parameters to do the queries.

**Comment by alexandermendes** [comment]
Ok great, so this might be a bit much for me to have a go at now but happy to give some input at some point!

**Comment by teleyinex** [comment]
Sure!!! Let's keep this open. I think the first thing we need to do is to upgrade to JSONB via an alembic migration. This will open the door to the new features. What do you think?

**Comment by alexandermendes** [comment]
Sounds good to me!

**Comment by alexandermendes** [comment]
Can close this one if you like - we're now storing our project tags in the info field but might also move to using a separate web annotation server for different types of tag (we're already using it to store our final results, so may as well make the most of it). 

The additional API queries mentioned above would be cool but that's probably a different/wider issue.

**Comment by teleyinex** [comment]
I think it could be an interesting feature. As soon as we add PostgreSQL 10.0 we will enable fulltext search within any JSONB object, so anyone will be able to filter in more ways ;-). I'll close it just to clean a bit the list of issues :D

**Comment by teleyinex** [comment]
Just found this:

```
SELECT * FROM users 
  WHERE metadata->>'countries' IN ('Chad', 'Japan');
```

We can do searches within JSONB in PYBOSSA. We only need to add support via the API to this type of operations. Would this work for you @alexandermendes?

**Comment by alexandermendes** [comment]
That could be a nice and clean solution actually. Even if we don't end up using it for these particular tags it sounds like it would be a useful feature to have!

**Comment by teleyinex** [comment]
I do agree :-) Let me think about how to implement it, but this should be inside PYBOSSA by all means ;-)

**Comment by teleyinex** [comment]
This can be done now via the api: /api/projects?info={'key': value}
