### ISSUE TITLE
Give admins access to all user fields via /api/user

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1722]
What do you think about giving admin users access to all (or at least, more) user fields via the API. I'm moving towards loading all domain objects via the standard API routes and have just hit the issue that I can't see the `admin` flag. Considering admins can see this via other API routes, I think it would make sense to make it available here too.

Actually, I've also wanted to check a few times in the past how a user signed up (twitter, facebook, google, regular sign up) and there's currently no way of getting to that without going into the database directly. Perhaps it would make sense to just let admin users see everything here (or nearly everything)?

**Comment by teleyinex** [comment]
Yes, we've seen the same. If you try to access your own user via the /api/user you will get less info that what you can get from /account/user/<name>. This is something that we need to fix asap.

**Comment by teleyinex** [comment]
Fixed!

**Comment by alexandermendes** [comment]
Ah yes I noticed, thanks 😄
