### ISSUE TITLE
Incorrect dashboard stats for New Users and New Contributions

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1741]
Just spotted this one, don't know where it's coming from yet but it's there on the default theme too (which is where the screenshot below is from).

![image](https://user-images.githubusercontent.com/5636273/32685255-9b82535e-c685-11e7-985e-e882b6fb2a5b.png)

For some reason today is appearing on the wrong side of the chart!

**Comment by teleyinex** [comment]
Hi,

Yes, I've seen that as well. It doesn't happen always. We need to check why is that.
