### ISSUE TITLE
Multiple project stats for one project

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1742]
Not sure how this has happened but I have a situation where we have multiple stats for one project, for example:

https://www.libcrowds.com/api/projectstats?project_id=66

So at some point the old row (ID 26 above) wasn't update and instead a new row was created (ID 58 above). I'll try to figure this out but though I would first be lazy and see if you have any ideas? :smile:

**Comment by teleyinex** [comment]
I think this is not relevant anymore, so closing it.
