### ISSUE TITLE
No easy way into draft projects in default theme

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1758]
As I finish off the admin page for our frontend we're still using the default theme for a couple of things. One thing I've noticed is that there is no easy way into the draft projects, see screenshot below - the more info button is missing.

![image](https://user-images.githubusercontent.com/5636273/33515398-9e631f3c-d75a-11e7-9716-87df64aa57dc.png)

**Comment by teleyinex** [comment]
Yep, that's a bug.
