### ISSUE TITLE
Endpoint for removing project tasks, taskruns and results

### ISSUE THREAD

**Issue by ppeczek** [Scifabric/pybossa#1760]
Pybossa lacks endpoint which would clear project.
- If project is not published it would remove all tasks, taskruns and results
- Else???

**Comment by teleyinex** [comment]
Webhooks
Auditlogs
ProjectStats
Counter table
else?

**Comment by teleyinex** [comment]
Closing as this is not relevant right now. Please, re-open if you need it.
