### ISSUE TITLE
Paginator in tasks browse doesn't include created tasks via API

### ISSUE THREAD

**Issue by ppeczek** [Scifabric/pybossa#1761]
If you import a hundred of tasks then you have 10 pages in `http://localhost:5000/project/{project_name}/tasks/browse/` . When you add 20 more by `pbclient.create_task(project_id, info)` then paginator doesn't include more pages, but `http://localhost:5000/project/{project_name}/tasks/browse/11` and `http://localhost:5000/project/{project_name}/tasks/browse/12` exist.

**Comment by teleyinex** [comment]
That's because of the counting is done within the background jobs. Thus, if you upload tons of tasks via the api, then, if the background job has not been ran, that info will not be available. This is done on purpose because when you have several projects that have hundred thousands of tasks, and their task_runs building those pages are *really expensive* :-)

**Comment by teleyinex** [comment]
This is a bug within the counter table.

**Comment by teleyinex** [comment]
@ppeczek can you check if in your DB, the table counter has only the first 100 items? I'm asking because we're using this for increasing/storing the info the counter table: https://github.com/Scifabric/pybossa/blob/55f8d9b9645c0b79bd47837457090f57850aec51/pybossa/model/event_listeners.py#L273

**Comment by teleyinex** [comment]
In any case, there's a bug as when a task is deleted the counter should be updated.

**Comment by ppeczek** [comment]
I've already tried many different operations in pybossa, including
deletions :/

11.12.2017 5:35 PM "Daniel Lombraña González" <notifications@github.com>
napisał(a):

**Comment by teleyinex** [comment]
Can you check the counter table?

**Comment by teleyinex** [comment]
I'll debug this with this PR as I will add a new test for your specific case.

**Comment by ppeczek** [comment]
I'll check it tomorrow morning

2017-12-11 17:38 GMT+01:00 Daniel Lombraña González <
notifications@github.com>:

**Comment by teleyinex** [comment]
The last commit shows that it works via the API as well, so as soon as this is green, I'll close this issue. In principle, it's fixed.
