### ISSUE TITLE
Publish projects via the API

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1762]
Am I right in thinking that there is no way to publish projects via the API? 

I can see it's disabled for the RESTful endpoint at `/api/project` but we also can't do it via `/project/<short_name>/publish` as that would require a CSRF token and as we're not dealing with a form here, none is returned.

This obviously needs to be sorted out for full SPAs, either by enabling it via the RESTful endpoint or making the other endpoint exempt from CSRF. Which one do you think is better?

**Comment by teleyinex** [comment]
I would say via the CSRF when requesting the publish endpoint, correct? That should do the trick. 

We disabled publishing via the api/project/<ID> because we think we want always to have a human to review that process. Thus, we included it within that frontend endpoint. What do you think?

**Comment by alexandermendes** [comment]
So one thing is that there isn't actually a form returned from `/<short_name>/publish` , so there is no CSRF token. It's also one of the endpoints where `handle_content_type` isn't implemented yet. That's easy enough to fix but perhaps a form also needs to be added for publishing projects, so that we can get that CSRF token?

**Comment by alexandermendes** [comment]
Ah ok, or just handle it like http://docs.pybossa.com/api/project/project/#project-delete and return a CSRF token on it's own. Can send a PR if that sounds reasonable!

**Comment by teleyinex** [comment]
Sounds really good!
