### ISSUE TITLE
Flickr importer not available

### ISSUE THREAD

**Issue by nicaogr** [Scifabric/pybossa#1773]
When I run "python run.py" after the installation I got a "Flickr importer not available" message. Do you know what could be the reason ?

Best,

**Comment by teleyinex** [comment]
Where? I would need a bit more of information :-) Can you tell us what you are trying to do and where it fails?

**Comment by nicaogr** [comment]
Hi,

I am trying to install Pybossa on my machine. I have follow the [Installation Guide](http://docs.pybossa.com/installation/guide/). And so I decided to try my installation, I run my web server. And I got this output message in the console : 

Slave binds are misssing, adding Master as slave too.
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter signin disabled
<type 'exceptions.KeyError'>
('FACEBOOK_APP_ID',)
'FACEBOOK_APP_ID'
Facebook signin disabled
<type 'exceptions.KeyError'>
('GOOGLE_CLIENT_ID',)
'GOOGLE_CLIENT_ID'
Google signin disabled
<type 'exceptions.KeyError'>
('FLICKR_API_KEY',)
'FLICKR_API_KEY'
Flickr importer not available
<type 'exceptions.KeyError'>
('DROPBOX_APP_KEY',)
'DROPBOX_APP_KEY'
Dropbox importer not available
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter importer not available
<type 'exceptions.KeyError'>
('YOUTUBE_API_SERVER_KEY',)
'YOUTUBE_API_SERVER_KEY'
Youtube importer not available
GeoLiteCity.dat file not found
Project page stats web map disabled
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Comment by alexandermendes** [comment]
See http://docs.pybossa.com/installation/configuration/#enabling-the-flickr-task-importer

**Comment by nicaogr** [comment]
Thanks a lot.

**Comment by teleyinex** [comment]
If this solves the issue, can you close it? Thanks!
