### ISSUE TITLE
Documentation page missing

### ISSUE THREAD

**Issue by nicaogr** [Scifabric/pybossa#1774]
The documentation about how to import data from a CSV file containing all the url is missing : https://docs.pybossa.com/en/latest/user/overview.html#importing-the-tasks-via-the-built-in-csv-task-creator

**Comment by teleyinex** [comment]
It's here: https://docs.pybossa.com/build/overview/#importing-the-tasks-via-the-built-in-csv-task-importer

Access docs.pybossa.com directly and search. We move the documentation to another software to provide a much better search engine.
