### ISSUE TITLE
Dropbox importer not available

### ISSUE THREAD

**Issue by vgutierrez9** [Scifabric/pybossa#1785]
Hi, the documentation notes that you can use a Pybossa Dropbox importer, however on server/project/shortname/tasks/import Dropbox is not listed as an available Pybossa importer.

**Comment by vgutierrez9** [comment]
As seen on: https://docs.pybossa.com/build/overview/#importing-the-tasks-from-a-dropbox-account

"For using this importer, just follow these are the steps:

    1. Navigate to your project’s page and click in the Tasks section.
    2. Then click on the Import Tasks button, and select the Dropbox importer.
    3. Click on the “Choose from Dropbox” icon. You will be asked your Dropbox account credentials. Then select as many files as you want: "

The Dropbox importer option in step 2 does not exist.

**Comment by teleyinex** [comment]
Hi,

Good catch. We've documented it here: https://docs.pybossa.com/installation/configuration/#enabling-the-dropbox-task-importer but we forgot to link it from that section. Just follow those steps, and the importer will be available.

Cheers

**Comment by teleyinex** [comment]
Fixes this issue: https://github.com/Scifabric/docs.pybossa.com/pull/22
