### ISSUE TITLE
Add category_id to results table

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1788]
With the new JSONB queries it would be really useful to be able to search results for a given category so that we can create a search interface for each. We have all of the other keys in the result (project_id, task_id, task_run_ids) but no way of searching all results in a single category with a single query. Could we add category_id to the results table?

**Comment by teleyinex** [comment]
This is really cool. I would say go for it @alexandermendes

**Comment by teleyinex** [comment]
@alexandermendes are you interested in building this?
