### ISSUE TITLE
SPARQL Importer

### ISSUE THREAD

**Issue by BonaBeavis** [Scifabric/pybossa#1798]
I like to write a SPARQL importer for pybossa. This importer should import tasks from a SPARQL endpoint by defining a SPARQL query and adding the result set as an bulk import.

Can I have some pointers how to implement this? First question I have is:
Should I extend the server or write a plugin?

**Comment by teleyinex** [comment]
Hi,

This would be a great great feature. I would add it to the upstream version, so forget about plugins :-)

Regarding how to do it. I would say, you would need to use a python library that supports SPARQL. Then, on the default theme, you will need to add a JS/input/whatever where people will type the query. The importer will get the query, send it to the endpoint, if it gets results, process them adding tasks.

NOTE: as this could return tons of tasks, I would follow the same approach that we do with the CSV importer. Above a certain number, we enqueue the creation of tasks, so the UI responds quickly.

Take a look at the importer folder for more information. If you need more help, you can always find us in Gitter and we would love to give you support!

**Comment by BonaBeavis** [comment]
Ok, I startet with the importer: [QROWD/pybossa at sparqlImporter](https://github.com/QROWD/pybossa/tree/sparqlImporter).
It is very barebones right now, it just create a task with the result bindings as task info. But it uses already the bulk import class.
I think a need some directions on how to setup testing any other input is welcome to naturally.

**Comment by teleyinex** [comment]
Open a PR so we can track differences, and we'll focus work there. Looking forward to this :-)

**Comment by BonaBeavis** [comment]
#1815
