### ISSUE TITLE
Is auto-import for S3 under consideration or off the table?

### ISSUE THREAD

**Issue by vgutierrez9** [Scifabric/pybossa#1801]
Hi, I was wondering if auto-import for S3 is not available because it is something that has just not been been looked into yet, or something that was considered and found not possible for some reason.

**Comment by teleyinex** [comment]
It's not off the table. Please, send us a pull request with support for S3 and we will help you with the code as well as merge into upstream. Would be happy to have it as well :-)

**Comment by vgutierrez9** [comment]
I'd love to help. Opening a pull request now, and would love help with some direction.

**Comment by teleyinex** [comment]
So, we're usually hanging out on [Gitter](https://gitter.im/Scifabric/pybossa) where you can chat with us. There're other people using PYBOSSA, so you can get help from several of us there.

Then, just use this issue to propose the changes, create a PR and move forward. We'll help you!

**Comment by teleyinex** [comment]
@vgutierrez9 closing this issue. Please, feel free to open it when you want to contribute back or if you need this feature again.
