### ISSUE TITLE
Clarification requested about SQLAlchemy in the install docs 

### ISSUE THREAD

**Issue by chrisranderson** [Scifabric/pybossa#1803]
https://docs.pybossa.com/installation/guide/ mentions "your SQLAlchemy DB URI", but there is no previous  mention of SQLAlchemy or how to determine the URI. How do I figure that out?

**Comment by teleyinex** [comment]
If you open the settings_local.py file, you will see that there's a variable/flag named like [this](https://github.com/Scifabric/pybossa/blob/master/settings_local.py.tmpl#L33):
```
SQLALCHEMY_DATABASE_URI = 'postgresql://pybossa:tester@localhost/pybossa'
```
Thus, there, you should write the URI to your PostgreSQL server, or in other words, where is it listening? 

Just type it there, save it, and you will be set.
