### ISSUE TITLE
Exporting tasks and task_run not working

### ISSUE THREAD

**Issue by mariohese** [Scifabric/pybossa#1804]
Exporting tasks and task_run button is not working, the server doesn't answer when the button is pushed.

For downloaded the files, in the URL the next query has to be entered:
server/project/projectshortname/tasks/export?type=task_run&format=json

Instead of task_run you can put task for downloading the questions json and in format instead of json it can be put csv

**Comment by teleyinex** [comment]
Can you check in your PostgreSQL database, the table project_stats? Do something like this:

```sql
select * from project_stats where project_id=ID
```

Put in ID the id of your project. If you get nothing there, then something is broken.

**Comment by teleyinex** [comment]
@mariohese I've now  a bit more of background. Are you running background jobs? If you are not, then we've an issue as project_stats table is updated via background jobs. As a result, that table returns everything with zeros, and you cannot get the link to the ZIP file.

For being sure that this is the issue, can you do the following? Go to your pybossa folder. Activate your virtualenv, and then open a python shell. From there, type the following:

```python
from run import create_app
from pybossa.jobs import get_project_stats
app = create_app(False)

with app.app_context():
   get_project_stats(ID, project_short_name)

```
It should run without any errors. Then, repeat the previous SQL query:

```
select * from project_stats where project_id=ID
```

If you use the same ID, that table should have now something inside. Can you check?

**Comment by teleyinex** [comment]
Closing this issue. Please @mariohese report in #1753
