### ISSUE TITLE
Large CSV file and Email Notification

### ISSUE THREAD

**Issue by sfluo** [Scifabric/pybossa#1808]
**Setting:**

If I try to import a large CSV, e.g. 1000+, it will notify say, you are uploading a very large CSV and the system will email me a notification when the task is ready. 

**Environment:**

1. I setup the send-only mail server using postfix in my ubuntu sever where pybossa is running, and I have received the email that I sent from command line in the ubuntu as blow:

$ echo "This is the body of the email x" | mail -s "This is a title" example@gmail.com

2. pybossa mail setting in setting_local.py
MAIL_SERVER = 'localhost'
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_PORT = 25
MAIL_FAIL_SILENTLY = False
MAIL_DEFAULT_SENDER = example@gmail.com

**Problem:**

1. after long wait, I did not see an email regarding the large CSV file I was trying to import 
2. I do not have any place to check how the import goes, in progress? failed? or cancelled?

If I am missing any steps, please kindly let me know. Appropriate that!

btw, do I have to build the image every time I modify the setting_local.py? I know I probably should send these questions to mail list? but what is the mail list address? I could not find a valid mail address for pybossa mailist though.

**Comment by teleyinex** [comment]
Hi,

No worries, we use issues or Stackoverflow for answering these questions :-) Feel at home.

I would say you have not received the email because you might not be running the background jobs. Are you? To check, go to the admin page, and click on Background Jobs. There you will be able to see if a job has failed, succeed or its status.

Please, let me know if this helped.

**Comment by sfluo** [comment]
you are right.. Thanks for guiding me. Still get gamily with the system

The upload of large CSV failed before the email being sent

 pybossa.jobs.import_tasks(1,
csv_filename='/opt/pybossa/uploads/user_1/xxx.csv', type='localCSV') from
*medium*
a31df961-44d0-4483-bd41-045f225e74ef
Failed 30 seconds ago

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line
479, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 466, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/pybossa/pybossa/jobs.py", line 501, in import_tasks
    report = importer.create_tasks(task_repo, project_id, **form_data)
  File "/opt/pybossa/pybossa/importers/importer.py", line 66, in create_tasks
    for task_data in importer.tasks():
  File "/opt/pybossa/pybossa/importers/csv.py", line 175, in tasks
    return self._get_csv_data_from_request(csv_filename)
  File "/opt/pybossa/pybossa/importers/csv.py", line 165, in
_get_csv_data_from_request
    raise BulkImportException(gettext(msg), 'error')
BulkImportException: ('Unable to load csv file for import, file
/opt/pybossa/uploads/user_1/xxx.csv', 'error')


I enabled ​ Account confirmation email and see Smtplib
Error 111, connection refused.

## Mail setup

MAIL_SERVER = '127.0.0.1'

MAIL_USERNAME = None

MAIL_PASSWORD = None

MAIL_PORT = 25

MAIL_FAIL_SILENTLY = False



Still googling, suggestions are welcome....



​Shoufu​


---
There is no such a thing called randomness.

**Comment by sfluo** [comment]
**update**: I think the connection error 111 is caused by the fact that I did not install mail server in the container but in the host, therefore, my previous test is invalid. If use vagrant, mail server can be installed after vagrant ssh; If use docker, install Mail server in the container (how?)

**Comment by teleyinex** [comment]
:-) We're working on migrating everything to Docker. However, we don't recommend to use your own SMTP server as the chances of getting your emails as spam are really high. Can you use your own Gmail/Yahoo account? That will do the trick.

**Comment by sfluo** [comment]
Yes. Email is not a big deal. The problem is when I setup with Docker, it fails to import large CSV file although it did successfully upload the file to /opt/pybossa/uploads/. Could not figure out the problem ...

**Comment by teleyinex** [comment]
Is this fixed?
