### ISSUE TITLE
project info

### ISSUE THREAD

**Issue by sfluo** [Scifabric/pybossa#1823]
how many tasks in total is not alway available. It can be browsed in the task browse card, which is not always accurate, however. In the project info card, it should be shown simply statistics that how many tasks, hoy many contributors, etc.

**Comment by teleyinex** [comment]
You have a new endpoint for that:

https://crowdcrafting.org/api/projectstats?project_id=120 

Thus, for your server, just replace the name of the server and use the PROJECT ID that you want to get.

NOTE: these values are updated based on your settings_local.py configuration. This means, that if you have a normal user, the stats will be updated by default every 24 hours. You can change that behavior by turning that user a PRO (check that flag to true in the DB) and then, it will be updated every 10 minutes.
