### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [Scifabric/pybossa#1825]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by teleyinex** [comment]
Hi,

Apologies for not getting back to you on this. We've a "logo" :-) It's just a typography, but we decided a long time ago to use it as way of simplifying our stuff :-)

In any case, thanks a lot!!!
