### ISSUE TITLE
Optionally restrict CRUD options for the API

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1828]
For the LibCrowds project we're now using a lot of custom fields in our `task`, `project` and `result` objects. The interface will only work properly if some of these fields exist.

Soon, we want to open up the creation of projects to all users. However, we would ideally only want them to be able to create and modify projects and tasks via our frontend. If we let users update these domain objects via the API they could easily break them. We would still want users to be able to read everything via the API, just not make any changes.

Can you think of a straightforward way that we might restrict the modification of these domain objects?Perhaps some kind of `API_WHITELIST` configuration setting that if enabled restricts API updates to listed servers. This could then be checked in [api_base.py](https://github.com/Scifabric/pybossa/blob/master/pybossa/api/api_base.py). What do you think?

**Comment by alexandermendes** [comment]
This is definitely nothing urgent - it's unlikely that many users would attempt to update things programatically - but some option like this would provide more stability in future.

**Comment by teleyinex** [comment]
Yes. Something on those lines will be good. Actually, PYBOSSA has right now a c[heck on attributes](https://github.com/Scifabric/pybossa/blob/master/pybossa/api/api_base.py#L453) to avoid updating for example the User ID or IP. Thus, it will be extending that check via a settings_local.py flag. What do you think?

**Comment by teleyinex** [comment]
And here an example: https://github.com/Scifabric/pybossa/blob/master/pybossa/api/task_run.py#L56

**Comment by encima** [comment]
I believe I am having a similar issue. I am creating an SDK for an Android based frontend and would like to be able to register a user via the Pybossa API, is this something that is coming or intentionally not being done (I know the docs mention it is not possible)?

**Comment by teleyinex** [comment]
@encima you can register a new user without problems. The account endpoints allow you to do that, actually in the docs you have a few examples: https://docs.pybossa.com/api/user/account/#account-registration

Is that what you need?

**Comment by teleyinex** [comment]
Also, a signin example: https://docs.pybossa.com/api/user/account/#account-sign-in

**Comment by encima** [comment]
Ah, yes, sorry for hijacking this issue then. Thanks!
