### ISSUE TITLE
Allow upload of local CSV rather than from remote URL

### ISSUE THREAD

**Issue by chrisranderson** [Scifabric/pybossa#1829]
Maybe I'm missing something. I'm looking at this:
![image](https://user-images.githubusercontent.com/5461398/38758783-e09b16ba-3f2f-11e8-9472-f412af28e8d8.png)
Is the only way I can use a CSV is if I take the one I make on my machine, upload it somewhere online, and then pass in a URL? If so, it would be great to upload ones from my computer.

**Comment by teleyinex** [comment]
Hi,

PYBOSSA allows you to upload a file to the server as well. But, yes, you can upload your CSV into Google Spreadsheets, then share it. Copy the sharing link and paste there, click import and you should get the tasks imported.

Also, the CSV file should be uploaded. Are you trying this on your own server?

**Comment by osecki** [comment]
This was added to pybossa here:

PR:  https://github.com/Scifabric/pybossa/pull/1659

Release:  https://github.com/Scifabric/pybossa/releases/tag/v2.7.0

**Comment by chrisranderson** [comment]
I found it - maybe it would be good to combine both CSV options (URL or upload) into a single page. I missed it because I was just looking for "CSV".

**Comment by teleyinex** [comment]
Well, both handle the same type, but I'm not sure right now. Basically, we want to improve the local CSV to as it doesn't work when you are using a cloud system to store user data. For now, let's keep it like this.

**Comment by teleyinex** [comment]
Closing it for the moment.
