### ISSUE TITLE
Importing tasks is broken

### ISSUE THREAD

**Issue by chrisranderson** [Scifabric/pybossa#1834]
At the URL `/project/quality_control_1/tasks/import`, this comes up:
![image](https://user-images.githubusercontent.com/5461398/39317412-c55bd2fa-4938-11e8-902d-3aa13b1960c9.png)

**Comment by chrisranderson** [comment]
Here is error information:
![image](https://user-images.githubusercontent.com/5461398/39317481-ec7a4646-4938-11e8-86c4-fafe01da38b7.png)

**Comment by teleyinex** [comment]
Can you try with the latest version of PYBOSSA?

**Comment by chrisranderson** [comment]
We're probably not going to use PYBOSSA at this point - sorry. Good luck with your project. You can close this if you want.

**Comment by teleyinex** [comment]
No problem
