### ISSUE TITLE
"Ooops, Something's wrong" on install

### ISSUE THREAD

**Issue by HristoBuyukliev** [Scifabric/pybossa#1837]
I followed the guide step-by-step, and I get this issue. Additionally, there is no useful information in the command line:

> python run.py 
Slave binds are misssing, adding Master as slave too.
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter signin disabled
<type 'exceptions.KeyError'>
('FACEBOOK_APP_ID',)
'FACEBOOK_APP_ID'
Facebook signin disabled
<type 'exceptions.KeyError'>
('GOOGLE_CLIENT_ID',)
'GOOGLE_CLIENT_ID'
Google signin disabled
<type 'exceptions.KeyError'>
('FLICKR_API_KEY',)
'FLICKR_API_KEY'
Flickr importer not available
<type 'exceptions.KeyError'>
('DROPBOX_APP_KEY',)
'DROPBOX_APP_KEY'
Dropbox importer not available
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter importer not available
<type 'exceptions.KeyError'>
('YOUTUBE_API_SERVER_KEY',)
'YOUTUBE_API_SERVER_KEY'
Youtube importer not available
> \* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
>127.0.0.1 - - [04/May/2018 15:30:45] "GET / HTTP/1.1" 500 -

And no error after the 500 status. 
However, if I change in the local_settings.py DEBUG = True, and run run.py, I get 
> sqlalchemy.exc.ProgrammingError
> ProgrammingError: (psycopg2.ProgrammingError) relation "project" does not exist LINE 4: FROM project, "user"

What is the cause of this and how can I fix it?

**Comment by teleyinex** [comment]
It looks like you have not created the DB in PostgreSQL. Can you check if you have the DB created and populated with its tables? Check the docs https://docs.pybossa.com/installation/guide/

**Comment by HristoBuyukliev** [comment]
Thanks, but I did have the database created. I actually created and destroyed it several times. Funny thing is, when I created the project anew, it worked. I guess either because the first time the virtualenv was not called "env", which I doubt, or because I forgot to run the task scheduler or whatever.

**Comment by teleyinex** [comment]
Good to know :D Then, can you close this issue if you don't have any issues? Thanks in advance!
