### ISSUE TITLE
Vagrant setup: populate PyBossa DB task fails

### ISSUE THREAD

**Issue by joetm** [Scifabric/pybossa#1841]
I am doing an install from a clean repo.
`vagrant up` fails at the DB population task.

> default: TASK [populate PyBossa DB] *****************************************************
>     default: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["/home/vagrant/pybossa-env/bin/python", "cli.py", "db_create"], "delta": "0:00:02.187642", "end": "2018-05-11 10:11:48.259697", "failed": true, "rc": 1, "start": "2018-05-11 10:11:46.072055", "stderr": "Traceback (most recent call last):\n  File \"cli.py\", line 19, in <module>\n    app = create_app(run_as_server=False)\n  File \"/vagrant/pybossa/core.py\", line 81, in create_app\n    anonymizer.init_app(app)\n  File \"/vagrant/pybossa/anonymizer/__init__.py\", line 30, in init_app\n    cp = CryptoPAn(app.config.get('CRYPTOPAN_KEY'))\n  File \"/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/yacryptopan.py\", line 60, in __init__\n    assert(len(key) == 32)\nTypeError: object of type 'NoneType' has no len()", "stdout": "Slave binds are misssing, adding Master as slave too.\n<type 'exceptions.KeyError'>\n('TWITTER_CONSUMER_KEY',)\n'TWITTER_CONSUMER_KEY'\nTwitter signin disabled\n<type 'exceptions.KeyError'>\n('FACEBOOK_APP_ID',)\n'FACEBOOK_APP_ID'\nFacebook signin disabled\n<type 'exceptions.KeyError'>\n('GOOGLE_CLIENT_ID',)\n'GOOGLE_CLIENT_ID'\nGoogle signin disabled\n<type 'exceptions.KeyError'>\n('FLICKR_API_KEY',)\n'FLICKR_API_KEY'\nFlickr importer not available\n<type 'exceptions.KeyError'>\n('DROPBOX_APP_KEY',)\n'DROPBOX_APP_KEY'\nDropbox importer not available\n<type 'exceptions.KeyError'>\n('TWITTER_CONSUMER_KEY',)\n'TWITTER_CONSUMER_KEY'\nTwitter importer not available\n<type 'exceptions.KeyError'>\n('YOUTUBE_API_SERVER_KEY',)\n'YOUTUBE_API_SERVER_KEY'\nYoutube importer not available", "stdout_lines": ["Slave binds are misssing, adding Master as slave too.", "<type 'exceptions.KeyError'>", "('TWITTER_CONSUMER_KEY',)", "'TWITTER_CONSUMER_KEY'", "Twitter signin disabled", "<type 'exceptions.KeyError'>", "('FACEBOOK_APP_ID',)", "'FACEBOOK_APP_ID'", "Facebook signin disabled", "<type 'exceptions.KeyError'>", "('GOOGLE_CLIENT_ID',)", "'GOOGLE_CLIENT_ID'", "Google signin disabled", "<type 'exceptions.KeyError'>", "('FLICKR_API_KEY',)", "'FLICKR_API_KEY'", "Flickr importer not available", "<type 'exceptions.KeyError'>", "('DROPBOX_APP_KEY',)", "'DROPBOX_APP_KEY'", "Dropbox importer not available", "<type 'exceptions.KeyError'>", "('TWITTER_CONSUMER_KEY',)", "'TWITTER_CONSUMER_KEY'", "Twitter importer not available", "<type 'exceptions.KeyError'>", "('YOUTUBE_API_SERVER_KEY',)", "'YOUTUBE_API_SERVER_KEY'", "Youtube importer not available"], "warnings": []}
>     default: 
>     default: PLAY RECAP *********************************************************************
>     default: 127.0.0.1                  : ok=21   changed=11   unreachable=0    failed=1

**Comment by alexandermendes** [comment]
Just pulled the latest version and can confirm this is an issue! Fix incoming...
