### ISSUE TITLE
Add stats param to projects endpoint

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1849]
Hi, sorry to keep bombarding you with issues (I'll try to clear some of the old ones soon) but what do you think about me adding a `stats=1` param to the `/api/project` endpoint, similar to how you use `related` to load related Tasks, Taskruns etc., to append the dictized project stats table to `project.stats`.

We've got various cases where we want to, for example, filter by `category_id`, have access to `owner_id` and sort by `overall_progress` or `n_tasks` etc. Currently, I can't find a nice way to do this without potentially a whole bunch of wasted API calls.

**Comment by teleyinex** [comment]
It sounds great. Go for it!!!

**Comment by alexandermendes** [comment]
Great thanks, will sort it out soon!
