### ISSUE TITLE
Flickr AutoImporter duplicates already-imported tasks

### ISSUE THREAD

**Issue by jacksongs** [Scifabric/pybossa#1854]
Hi folks,

I have had the Flickr AutoImporter running for about 8 months successfully, but it recently starting duplicating tasks. I've had to kill the background worker as a temporary solution.

I've tried to replicate the problem on a local instance, but troubleshooting has been hard as I can't tell where the AutoImporter leaves logs/errors. Can I manually run the background task from the command line? Anything else you suggest I try?

**Comment by teleyinex** [comment]
Apologies for not getting back sooner. We're really checking all the corner cases of GDPR. As soon as we finish, (we think today) we will help you with this issue.

**Comment by teleyinex** [comment]
OK, I've done a quick check with the latest versio nof PYBOSSA and it imports without problems the tasks. Quick question: are you importing the same pictures for another project?

**Comment by teleyinex** [comment]
I've checked duplications within the same project, and PYBOSSA does not import the same photos. Would you mind to tell us more about how do you import the tasks?

**Comment by jacksongs** [comment]
Hi Daniel, thanks for having a look at this.

Each project is associated with a Flickr album id as part of the info field in the project table, ie:

`{"thumbnail": "E5D.JPG", **"autoimporter": {"type": "flickr", "album_id": 72157688600718545, "last_import_meta": null}**, "task_presenter": "\n        <link type=\"text/css\" rel=\"stylesheet\" href=\"/static/css/style.css\">\n    \t<div class=\"container\">\n\n    \t\t<div class=\"col-xs-12 col-md-8\">\n\t    \t\t<section id=\"pan-when-zoomed\">\n\t\t\t      \t<div id=\"img_container\">\n\t\t\t\t      \t<div class=\"...`

It has been working great until a week and a half ago.

I will set up a local instance with a dump of my database to continue testing. Is there anywhere I can check the logs of the worker (and if possible, edit the AutoImporter code to include some log messages)?

**Comment by jacksongs** [comment]
Hello again. I have merged in changes from 2.9.5 into my repo and oddly the problem has ceased. No idea why. I'll close this but will keep an eye on things.

**Comment by teleyinex** [comment]
Great. Let us know if this happens again.
