### ISSUE TITLE
questions about nginx 

### ISSUE THREAD

**Issue by sfluo** [Scifabric/pybossa#1856]
Try to understand how pybossa is built over nginx. Found contrib/nginx, but I did not see any place to configure nginx for pybossa. And what is the script type of contrib/nginx/pybossa? Any hints?

**Comment by teleyinex** [comment]
You will have to run PYBOSSA under wsgi. Then you can use any web server, like Apache or Nginx to serve it via wsgi modules. The config that you find there is for nginx server. In the past we used Apache ;-)

You have more info in the documentation: https://docs.pybossa.com/installation/deployment/
