### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by transfluxus** [Scifabric/pybossa#1877]
I see the installation docs say python <3.0.
I didn't try it yet, just wanna evaluate pybossa.
Is there any chance this would work in python 3, or what is the problem?

**Comment by normangilmore** [comment]
If you are evaluating Pybossa itself and not the process of installing Pybossa, I suggest checking out one of the containerized demos.

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=pybossa&starCount=0

disclosure:
goodly/pybossa is the one I configured, the source is here:
https://github.com/Goodly/pybossa-build

**Comment by transfluxus** [comment]
Hi Norman,

right, I wanted to have a first look before I go through the complete installation process.
How is the docker build different from the vagrant version?

Anyway, I got used to Python3 since quite a while and wouldn't like to go back for a larger project, so I wonder were hangs in python2.

**Comment by normangilmore** [comment]
I don't know about the other docker builds, my docker build followed the Vagrant approach with the ansible playbook.

I don't work on Pybossa core, so can't answer about Python3.

**Comment by teleyinex** [comment]
Regarding Python 3: we want to move everything to Python 3 asap. We're working on it, but dumped with other stuff :D Any help will be welcome!

**Comment by transfluxus** [comment]
cool, thanks Daniel,

I'll be starting at the ICTA in winter, so we'll probably talk at some point I guess :)

**Comment by teleyinex** [comment]
Hi,

We've finally migrated PYBOSSA to python 3 :-) We're looking for testers, so please, feel free to download the migrate-python3 branch and test it. You have more info in the README.

Cheers,

Daniel
