### ISSUE TITLE
Google Sign In doesn't show up till you complete Age Check

### ISSUE THREAD

**Issue by stephen-fisico-edmodo** [Scifabric/pybossa#1880]
Problem:
You shouldn't need to have your age checked before you can sign into via Google. 

Expected behavior: 
1. Go to your settings_local.py
2. Setup your GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
3. Run PyBossa
4. Open Incognito window and go to your Pybossa site
5. Click "Sign In" in the top right corner
6. You should see the orange Google Sign in button

Steps to reproduce the issue:
1. Go to your settings_local.py
2. Setup your GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
3. Run PyBossa
4. Open Incognito window and go to your Pybossa site
5. Click "Sign In" in the top right corner
6. Notice that orange Google Sign in button doesn't show up
7. Click on "Sign up for free now"
8. Put in your date of birth and click "Check Age"
9. Click on "Sign in" on the top right corner
10. You should notice that the orange Google Sign in button should show up now

**Comment by teleyinex** [comment]
Hi,

You have to check for the age, because the GDPR law requires you to do it. That's why, we have to check it before you can sign or create an account via Google, Twitter or Facebook Social Logins.

Cheers,

Daniel

**Comment by stephen-fisico-edmodo** [comment]
But it's extremely confusing UI. I didn't realize it was that way until I played around. Would it be possible to have the Google button show up anyways, then when the users click on the Google button, have them verify their age before they can log in for Google?

**Comment by teleyinex** [comment]
We do the opposite. As this is a template, you can customize it to whatever you like. The issue is that when you click in the Google button, you get the authentication against Google and therefore we cannot check it. Thus, we ask you first for your age, you type it, and then, you can get to Google. Since then, we have a cookie that doesn't ask you to verify again, and the Google button is shown.
