### ISSUE TITLE
Duplicate function update_project_stats in cli.py

### ISSUE THREAD

**Issue by normangilmore** [Scifabric/pybossa#1888]
The function `update_project_stats` is defined twice in cli.py at these two locations:

https://github.com/Scifabric/pybossa/blob/master/cli.py#L618
https://github.com/Scifabric/pybossa/blob/master/cli.py#L664

**Comment by teleyinex** [comment]
We have a different code, but the same name. Thanks for the report. We'll fix it! You can send as well a PR.
