### ISSUE TITLE
Disabling projects for further contributions

### ISSUE THREAD

**Issue by pdekker12** [Scifabric/pybossa#1891]
It would be nice to have the possibility to disable a project for further contributions. In our use case, we run a project for eg. a month. After that month, we would like no more contributions, while still being able to access the results ourselves.

Is this possible in any way at the moment? Or would it be possible to add this feature in the future?

**Comment by teleyinex** [comment]
Right now the easiest solution would be to password protect the project. In that way, only the users with that password would be able to participate.

**Comment by teleyinex** [comment]
Closing this, as I think that solution works for now. If you need to open it again, go for it.
