### ISSUE TITLE
Browse tasks page does not paginate

### ISSUE THREAD

**Issue by munterkalmsteiner** [Scifabric/pybossa#1907]
The browse tasks page shows only 10 tasks, even though more tasks were imported:
[tasks.txt](https://github.com/Scifabric/pybossa/files/2680594/tasks.txt)

The tasks are imported from a local CSV file.

I've enabled logging in settings_local.py:
LOG_FILE = '/tmp/pb.log'
import logging
LOG_LEVEL = logging.DEBUG

... but the log file stays empty.
There's some output from pybossa on the console:
[...]
127.0.0.1 - - [14/Dec/2018 16:30:15] "GET /admin/rq/queues.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:16] "GET /admin/rq/workers.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:17] "GET /admin/rq/jobs/failed/1.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:18] "GET /admin/rq/queues.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:19] "GET /admin/rq/workers.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:20] "GET /admin/rq/jobs/failed/1.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:21] "GET /admin/rq/queues.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:22] "GET /admin/rq/workers.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:23] "GET /admin/rq/jobs/failed/1.json HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:30:24] "GET /admin/rq/queues.json HTTP/1.1" 200 -
[... repeats ad infinitum]

The content of /admin/rq/jobs/failed/1.json is:
{"jobs":[],"name":"failed","pagination":{"pages_in_window":[]}}

This is with pybossa up-to-date master branch.

**Comment by teleyinex** [comment]
Hi,

This happens because that table is populated by one of the background jobs. Thus, you don't get the pages automatically, until the job is run. Can you check in your server if the background jobs are running?

**Comment by munterkalmsteiner** [comment]
Hi!
I'm starting the background jobs as follows:
`python app_context_rqworker.py scheduled_jobs super high medium low email maintenance`

... leading to the output:
```
Slave binds are misssing, adding Master as slave too.
/home/mun/development/sekraut/pybossa/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter signin disabled
<type 'exceptions.KeyError'>
('FACEBOOK_APP_ID',)
'FACEBOOK_APP_ID'
Facebook signin disabled
<type 'exceptions.KeyError'>
('GOOGLE_CLIENT_ID',)
'GOOGLE_CLIENT_ID'
Google signin disabled
<type 'exceptions.KeyError'>
('FLICKR_API_KEY',)
'FLICKR_API_KEY'
Flickr importer not available
<type 'exceptions.KeyError'>
('DROPBOX_APP_KEY',)
'DROPBOX_APP_KEY'
Dropbox importer not available
<type 'exceptions.KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter importer not available
<type 'exceptions.KeyError'>
('YOUTUBE_API_SERVER_KEY',)
'YOUTUBE_API_SERVER_KEY'
Youtube importer not available
10:33:26 RQ worker started, version 0.4.6
10:33:26 
10:33:26 *** Listening on scheduled_jobs, super, high, medium, low, email, maintenance...
```
Here's a screenshot of the background job dashboard.
![screenshot_2018-12-17 rq dashboard](https://user-images.githubusercontent.com/720692/50078902-70526800-01e8-11e9-8181-5099c3658ae5.png)

How can I check whether the background jobs are running? 
I've set logging (see my first post), but the log file stays empty...

**Comment by munterkalmsteiner** [comment]
Found the problem. The background jobs were running, but the scheduler was not. Hence, running
`rqscheduler --host localhost`
solved the issue.
