### ISSUE TITLE
retrieve new task with external user ids

### ISSUE THREAD

**Issue by ReedShalazi** [Scifabric/pybossa#1914]
Hello everyone!

I use external user ids and try to retrieve a task from the API, from `/api/project/<project_id>/newtask`.
However, it fails with a "This project does not allow anonymous contributors" error.

Is it an expected behaviour? In my view, It is not really anonymous since I can trace the user.
I thought it would work, as long as I use an authorization header with a retrieved token for that particular project.

I am surely missing something... 🤔 

Thanks for you help!

**Comment by teleyinex** [comment]
Did you disable the anonymous flag in the project? This could be the problem, and worthy to discuss :-) It's an anonymous user from the point of view of PYBOSSA, because the user doesn't have an internal ID.

**Comment by ReedShalazi** [comment]
Oh, I see, so it is just a question of vocabulary!
It is fine, I activated anonymous flags for projects.
I must admit it is a bit confusing at first, because pybossa is able to trace the user, and entrusts you with it, but name it "anonymous" as for really-anonymous ones... :)

**Comment by teleyinex** [comment]
Yes, I need to come up with a better name :D
