### ISSUE TITLE
New features for browse tasks

### ISSUE THREAD

**Issue by dchhabda** [Scifabric/pybossa#1915]
I am planning to contribute enhancement to browse task functionality. This would add following features to browse task.
1. Display task attributes such as priority, create date, complete date.
2. Ability to update task redundancy and priority.
3. Filter tasks by task field values.
4. Custom column display; show/hide columns of interest out of #1.
5. Delete tasks
6. Export tasks, taskruns.

@teleyinex , do you think that this would be a useful feature to contribute?

**Comment by teleyinex** [comment]
Hi,

This is great :-) A few comments, as I think some of the features are there, but not in the browse page:

1.- Display task attributes such as priority, create date, complete date: Yes. Go for it.!
2.- Ability to update task redundancy and priority: we've a section for that in the tasks settings. Why is this one not working for you?
3.- Filter tasks by task field values: Go for it :-) Note the info field is really freeform, so this could be "complicated"
4.- Custom column display: Go for it.
5.- Delete tasks: it will be great to have this feature. Note: you cannot delete a task if it has been completed.
6.- Export task and taskruns: we've specific sections for this. Why those sections are not working for you?

Thus, go for it. How do you want to implement it? Most of these items could be solved using only the API and writing the frontend without having to affect the backend. Do you want to do it on the frontend or backend?

**Comment by teleyinex** [comment]
Also, I'm in the process of migrating to Python3, so we need to be sure that your code can run in 3.5 as well, otherwise we cannot merge it. I could help with that :-)

**Comment by dchhabda** [comment]
Thanks @teleyinex for the reply. Current implementation for #2 and #6 works well, adding them to browse task is just to provide more flexibility to the user and avoid additional clicks. However, if you think these features to not part of browse task, we can skip including them here.

Our current implementation is here https://github.com/bloomberg/pybossa/blob/master/pybossa/view/projects.py#L1236, more of backend. If you think it would be good to have it in frontend, we can implement it that way. I will also keep note of python 3.5. 

Thanks again

**Comment by teleyinex** [comment]
Hi,

I was trying to understand all the issues :-) And you have been really convincing. Thus, go ahead and send the PR. I think it could be cool to have it in the backend as well, so we can leverage that part as well. I was thinking of doing this on the frontend, because nowadays we usually only develop for the API, decoupling everything. We've done all our recent work with VueJS, as the APIs give us, for now, all the flexibility that we need.

What do you think?

**Comment by dchhabda** [comment]
Sounds good. I'll go ahead and start working on PR. I take note of implementation under API wherever it fits best under API. Thanks.

**Comment by teleyinex** [comment]
Hi,

Quick question: would be too much work for you if we merge the python3 branch into master and you adapt your changes to run on python3?

**Comment by dchhabda** [comment]
Yes, I think it make sense to adapt python3 changes. I'm not expecting too much work, although this might take some additional time.

**Comment by teleyinex** [comment]
Perfect. This week I'm adding a new feature to PYBOSSA, so as soon as that it's merged, I'll merge as well the python3 branch so we work from now on on Python3 ;-) It's going to be a wild ride :D

**Comment by teleyinex** [comment]
Closing as there're no updates since almost a year. If you want to keep working on it, please, re-open it.
