### ISSUE TITLE
Deploy pybossa on a sub path

### ISSUE THREAD

**Issue by kreetrapper** [Scifabric/pybossa#1916]
I would like to deploy pybossa on a sub path of my server, i.e. not on http://my-server.eu but on http://my-server.eu/pybossa. But I am having trouble figuring out where and how I need to tweak the configuration to make this work. Just changing the value of SERVER_NAME in settings_local.py is not enough. 

`SERVER_NAME = my-server.eu/pybossa/`

This makes the css work fine, but the app does not know which content to serve, which means that all pages are 404s. 

I also tried to adjust the blueprints in core.py:

`blueprints = [{'handler': home, 'url_prefix': '/pybossa/'}, `
`                       {'handler': api,  'url_prefix': '/pybossa/api'},`
...and so on.

This makes the app work fine, but the css is not working, resulting in virtually unusable pages. 

When I combine both of these approaches, it doesn't work either. Then the css is fine, but the app does not respond. And additionally all the links in the menus are wrong, pointing to, e.g. 
`https://my-server.eu/pybossa/pybossa/help/api`

For reference, I am using the uwsgi/nginx setup, as described in https://docs.pybossa.com/installation/deployment/. I am using docker-compose, so you can see my whole setup (without those changes) at https://gitlab.inf.unibz.it/commul/docker/pybossa/tree/docker-compose.

**Comment by teleyinex** [comment]
Hi,

We've never done this before. We've always used a subdomain or the root domain for deploying it.

I've done a quick search on Google, and this looks promising: https://stackoverflow.com/a/34720894/1960596

Can you try?

**Comment by teleyinex** [comment]
I'm closing it due to inactivity. Please, re-open if needed.

**Comment by dennispaulino** [comment]
I had the same problem as mentioned by kreetrapper. I´ve implemented the solution of adjusting the path in the blueprints (core.py) suggested by the OP and it has worked.

**Comment by teleyinex** [comment]
Thanks for the follow up.
