### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by peterdekker** [Scifabric/pybossa#1930]
In my instance of PYBOSSA, I see the following message in my browser console on many pages:
`ReferenceError: $ is not defined`
The pages seem to work fine, but for some reason Jquery is not loaded at the right moment?

**Comment by teleyinex** [comment]
Hi,

This could be an issue with the current default theme. Can you list here which pages are having these issues? 

Thanks a lot.

**Comment by peterdekker** [comment]
I experience the problem (at least) on the following pages:
https://pybossa.taalradar.ivdnt.org/project/new
https://pybossa.taalradar.ivdnt.org/account/

**Comment by teleyinex** [comment]
Closing this issue. It has been more than a year.
