### ISSUE TITLE
redis.exceptions.ResponseError: unknown command

### ISSUE THREAD

**Issue by kuraga** [Scifabric/pybossa#1949]
Good day!

I get errors `redis.exceptions.ResponseError: unknown command '<ZRANGEBYSCORE, HWSET, etc.>'` on starting Pybossa 2.13.1 via Ubuntu's 19.10 Docker (with [redis-sentinel 5.0.5](https://packages.ubuntu.com/ru/eoan/redis-sentinel)).

Are there some ideas on this issue? Thanks.

**Comment by teleyinex** [comment]
This is really strange. We're running the tests using the latest version of redis from docker hub and the tests pass without problems. Can you give us more information?

**Comment by kuraga** [comment]
Sorry, I can't. Left Pybossa. Feel free to close.
