### ISSUE TITLE
Migration to authlib

### ISSUE THREAD

**Issue by cerquide** [Scifabric/pybossa#1959]
I see that you are using Flask-OAuthlib for OAuth authentication. It would be better to replace it with Authlib since Flask-OAuthlib is deprecated.

Here is a guide: https://blog.authlib.org/2018/migrate-flask-oauthlib-client-to-authlib

And there are many built-in connections in https://github.com/authlib/loginpass which can be used directly. 
Checkout Authlib repository: https://github.com/lepture/authlib
Authlib documentation: https://docs.authlib.org/

**Comment by teleyinex** [comment]
Hi,

Yes, this is great! Would you be willing to send a PR with such migration? I would be happy to merge it!

Cheers

**Comment by teleyinex** [comment]
Please, re-open it if you want to send the PR so we can have the work done within this issue.
