### ISSUE TITLE
Problems to bring up a pybossa instance

### ISSUE THREAD

**Issue by cerquide** [Scifabric/pybossa#1960]
It seems impossible to install a pybossa environment according to the requirements which are specified in setup.py. 

I have tried manual install following the instructions on the documentation and automated install using vagrant. Both processes fail. Because it is impossible to install exactly the versions which are fixed in setup.py. 

Relaxing versioning constraints, the only problem which seems to remain is the oauthlib version and this will be easy to solve if issue https://github.com/Scifabric/pybossa/issues/1959 is fixed.

**Comment by teleyinex** [comment]
Hi,

I've tried to install PYBOSSA in a new setup and it works without problems. All the dependencies are installed. Vagrant could be failing, but by manual installation, it works. Can you give me more details about it?

**Comment by teleyinex** [comment]
Ok, I've found the issue: with pip install -r requirements.txt it fails, but I've been isntalling it lately with pip install -e . Can you try it with that command instead?

**Comment by teleyinex** [comment]
Also, I've identified the lib problems, so this is PR for fixing it: https://github.com/Scifabric/pybossa/pull/1961

**Comment by teleyinex** [comment]
Fixed! Please, test it again, and let me know if you still have problems!

**Comment by cerquide** [comment]
Hi Daniel,

I have tried it and still got some problems with pyrax. I have submitted a PR #1964 correcting them and fixing the installation so that it also works in Python 3.8.
