### ISSUE TITLE
Upgrade to Python3.7 makes the created field on task_runs a hex string instead of a datestring

### ISSUE THREAD

**Issue by cravindra** [Scifabric/pybossa#1969]
Hello.

I noticed that the `retrieve_timestamp` method in `pybossa/pybossa/contributions_guard.py` returns a byte array value like ` b'2020-02-12T15:28:43.496205'`

And, the `_add_created_timestamp` method in `pybossa/pybossa/api/task_run.py`  assigns it's value directly as `taskrun.created = guard.retrieve_timestamp(task, get_user_id_or_ip())`

While this would've worked in Python 2 as the `b` prefix is ignored in a string like  `b'2020-02-12T15:28:43.496205'` but it creates a hex value when stored into the db in Python 3.7 (`"\\x323032302d30322d31325431353a30313a32342e383031373338"`)

See this SO post: https://stackoverflow.com/a/6269785/2649853

I believe something like this can fix the code:

```python
    def retrieve_timestamp(self, task, user):
        key = self._create_key(task, user)
        # return self.conn.get(key)
       return self.conn.get(key).decode()
```

I'd be happy to create a PR with this fix (and maybe a method in `cli.py` to fix preexisting entries) if that's the right way to go

**Comment by teleyinex** [comment]
Yes, please. Send a PR and we will check it. Thanks for reporting and wanting to contribute to the project.
