### ISSUE TITLE
crowdcrafting.org gives 404

### ISSUE THREAD

**Issue by reynoldsnlp** [Scifabric/pybossa#1975]
I tried going to https://crowdcrafting.org/ but I get a 404 status and the following html:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by teleyinex** [comment]
Hi,

Crowdcrafting was closed on April 2019, so that 404 it's ok :D

But, where did you find the link into it? I want to check, so I can update it.

**Comment by reynoldsnlp** [comment]
@teleyinex 

* https://pybossa.com/
* https://pybossa.com/getinspired/
* https://docs.pybossa.com/build/intro/

...and maybe others. You should probably just `grep -r` all of your repositories.

**Comment by playhere** [comment]
> Hi,
> 
> Crowdcrafting was closed on April 2019, so that 404 it's ok :D
> 
> But, where did you find the link into it? I want to check, so I can update it.

https://github.com/Scifabric/pybossa , there is a link 
👉 Play with PYBOSSA online

**Comment by playhere** [comment]
> Hi,
> 
> Crowdcrafting was closed on April 2019, so that 404 it's ok :D
> 
> But, where did you find the link into it? I want to check, so I can update it.

do we have any alternative site to experience pybossa, cause the installation is really time consuming.

**Comment by teleyinex** [comment]
Thanks to both! I've updated the docs, apologies for forgetting those links!

@playhere unfortunately no. You will have to run your own server, or you can hire Scifabric to setup one for you!
