### ISSUE TITLE
Task importer: Azure blob

### ISSUE THREAD

**Issue by eyast** [Scifabric/pybossa#1976]
Hi - the documentation mentions to post an issue if there's a request to add a new task importer. I think Azure blobs are an addition needed
BTW - thanks for Pybossa - i cant wait to try it completely end to end

**Comment by teleyinex** [comment]
Can you share more information about the Azure Blobs and what you want to do with them?

PS: Thanks for letting us know that you like our software!

**Comment by teleyinex** [comment]
Closing as this issue has not received any further feedback. Please @eyast re-open it when you want.
