### ISSUE TITLE
Pre populate tasks' answers

### ISSUE THREAD

**Issue by eyast** [Scifabric/pybossa#1977]
Is it possible to pre-populate the answers of tasks?
We've used an ML model to transcribe text, and the accuracy is very low. we want to now use Pybossa to distribute tasks for people to "fix" the transcription. if we were to create a new task presenter for the job, would it be possible to prepopulate a text field with what we've already modeled in ML?
Akin to the PDF transcriber, but without an empty text box per task

**Comment by teleyinex** [comment]
Hi!

Yes, you can pre-populate the tasks with any information that you want. The task.info field is a JSONB object within the PostgreSQL database, so you can have something like this:

```
{
"options": [ {"text": "option 1", "val": "value1"}, {"text": "option 2", "val": "value2"}]
}

```

Then you can present the user with different options (like a select or radio button) based on that options field. 

I hope this helps!
