### ISSUE TITLE
Failed to connect to web-server

### ISSUE THREAD

**Issue by adham-test** [Scifabric/pybossa#1985]
Hello everyone, 
I'm trying to install pybossa on Ubuntu server 18.04 on GCP, and it all worked fine, till the moment i run **python run.py** , 

this what i get

 ```
/home/adham_nawito/pb/pybossa/pybossa/extensions.py:112: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
Slave binds are misssing, adding Master as slave too.
/home/adham_nawito/pb_env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/home/adham_nawito/pb/pybossa/pybossa/core.py:621: FlaskWTFDeprecationWarning: "@csrf.error_handler" is deprecated. Use the standard Flask error system with "@app.errorhandler(CSRFError)" instead. This will be removed in 1.0.
 @csrf.error_handler
<class 'KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter signin disabled
<class 'KeyError'>
('FACEBOOK_APP_ID',)
'FACEBOOK_APP_ID'
Facebook signin disabled
<class 'KeyError'>
('GOOGLE_CLIENT_ID',)
'GOOGLE_CLIENT_ID'
Google signin disabled
<class 'KeyError'>
('FLICKR_API_KEY',)
'FLICKR_API_KEY'
Flickr importer not available
<class 'KeyError'>
('DROPBOX_APP_KEY',)
'DROPBOX_APP_KEY'
Dropbox importer not available
<class 'KeyError'>
('TWITTER_CONSUMER_KEY',)
'TWITTER_CONSUMER_KEY'
Twitter importer not available
<class 'KeyError'>
('YOUTUBE_API_SERVER_KEY',)
'YOUTUBE_API_SERVER_KEY'
Youtube importer not available
  Serving Flask app "pybossa.core" (lazy loading)
  Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
  Debug mode: off
  Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

when i try further more to connect to 

> when i try to click on the provided link `Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)` -->400. That’s an error. The requested URL was not found on this server. That’s all we know.

> (manualy) http://0.0.0.0:5000/  --> This site can’t be reached

> http://127.0.0.1:5000/ ---> This site can’t be reached 127.0.0.1 refused to connect.

> http://myServerIp:5000/ -->This site can’t be reached myServerIp took too long to respond.

Any solution how to connect to Pybossa ?

**Comment by teleyinex** [comment]
Have you configured the SERVER_NAME in the settings_local.py file?

**Comment by adham-test** [comment]
No, I didn't do that.  Do you mean by server_name just the name of the instance on GCP ?

**Comment by adham-test** [comment]
I assumed that (SERVER_NAME) is the instance name, so i changed my **settings_local.py** to this
![pybossa](https://user-images.githubusercontent.com/63200125/84038667-7e79e280-a9a0-11ea-9e17-96f65304e758.png)
and commented the line for HOST = 0.0.0.0
so it's now `#HOST = 0.0.0.0`

and it provides me new error .. 
![error 400](https://user-images.githubusercontent.com/63200125/84038722-90f41c00-a9a0-11ea-9f09-ddd7e03bf5cc.png)


please tell me if I'm doing it right or i'm missing something here.

**Comment by adham-test** [comment]
PS: this is not a production server, it's a test environment.. but I'm trying to run it Ubuntu server i've made on GCP, so I don't have a www.xyz.come i only have (server public IP) that i connect to this server through.

**Comment by teleyinex** [comment]
If you are running the server without a domain configured, then, go the settings file and comment the line SERVER_NAME='pybossa'. That should not be enabled, can you try again with that?

**Comment by teleyinex** [comment]
Closing this issue, as no further information for several months. Please re-open it again if you need to.
