### ISSUE TITLE
Restrict Pybossa API calls for admin users

### ISSUE THREAD

**Issue by Nits2097** [Scifabric/pybossa#1993]
I want to refactor the code to restrict use of all API calls to admin users only. Is there any easy workaround for that?

**Comment by teleyinex** [comment]
I guess you can do that, but why do you want to do this? It would be helpful if you explain the reasoning behind your idea, so we can help you.

**Comment by Nits2097** [comment]
In our business case, we are mainly using Pybossa for corporate crowdsourcing. We have thought of three types of user groups for the same, the administrators, the game masters and the game players. I want to allow only the admins and the game masters to access api calls to export task runs and results and restrict normal game players from doing that. So I wanted to know if there is any easy solution for it?
