### ISSUE TITLE
Base url for Pybossa

### ISSUE THREAD

**Issue by Nits2097** [Scifabric/pybossa#1995]
In case I want to host the flask app using a base url, my redirection worked, but none of my static files are loading. All files using /static are html pages and I am unable to configure the base url easily into that. Is there any easy way around it? Or would we have to add the base url in a hard coded fashion in all html files?

**Comment by teleyinex** [comment]
You should configure Nginx properly to serve those files. Check the contrib folder for some examples, also the official Flask documentation regarding deployments.
