### ISSUE TITLE
supervisor redis-sentinel conf file

### ISSUE THREAD

**Issue by jeanphilippegoldman** [Scifabric/pybossa#1999]
https://github.com/Scifabric/pybossa/blob/c9c6f7480ee5b8f5b9518e819c9c6592e60de64d/contrib/supervisor/redis-sentinel.conf#L2

shouldn't this line be rather this ? :
command=/usr/bin/redis-server /etc/redis/sentinel.conf --sentinel

**Comment by teleyinex** [comment]
Well, we have created the redis-sentinel script to avoid adding the --sentinel flag, but yes, that would work as well. See this file: https://github.com/Scifabric/pybossa/blob/master/contrib/redis/redis-sentinel.service
