### ISSUE TITLE
Removing Flickr importer

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#2015]
PYBOSSA has several integrations with third-party services like Flickr. These integrations were designed with Crowdcrafting in mind, but in the last years, almost all tasks have been created within PYBOSSA using CSV or JSON files via its API. Thus, that importer is no longer interesting, and we will focus more on improving CSV and JSON imports. It makes more sense to focus on an open format like CSV or JSON that can be created from any programming language from any external service (if it has an API).

**Comment by teleyinex** [comment]
This has been removed on version [4.0](https://github.com/Scifabric/pybossa/releases/tag/v4.0.0)

**Comment by portableant** [comment]
This was the importer we used most frequently on MicroPasts, sad to see it deprecated...
